### ISSUE TITLE
"Do you want to load additional keys?" Answer inverted

### ISSUE THREAD

**Issue by LeoVerto** [dlech/KeeAgent#100]
Line 735 in KeeAgentExt.cs should probably be `exitFor = false;`.

Not worth setting up a dev env and pull requesting, is it?

**Comment by dlech** [comment]
Did you actually observe a problem when running KeeAgent or is this just based on code inspection?

And if it is wrong , the correct fix would be to change [line 734](https://github.com/dlech/KeeAgent/blob/master/KeeAgent/KeeAgentExt.cs#L734) to

    if (!MessageService.AskYesNo(...

Tip: You can edit source code files directly in GitHub and do a pull request for simple changes like this.

**Comment by LeoVerto** [comment]
I observed the issue when KeePass attempts to load multiple invalid keys at startup.

**Comment by dlech** [comment]
I you would like to do a pull request, I'll take it, otherwise I will get around to it in a few days probably.

**Comment by dlech** [comment]
I have included your patch in http://files.lechnology.com/keeagent/0.6.0.1/KeeAgent.plgx.zip

Please try it out and let me know if you run into problems.

**Comment by LeoVerto** [comment]
Works correctly now, thanks!
