### ISSUE TITLE
KeeAgent Error when unlocking KeePass database with locked KeeAgent

### ISSUE THREAD

**Issue by chrahunt** [dlech/KeeAgent#102]
This occurs in Windows 7 x64 with KeePass 2.28. I initially noticed the issue in KeeAgent v0.4.1.0. I upgraded to v0.6.0.0 as a first step to troubleshoot the issue and it still occurs. KeeAgent is running in Agent Mode. No other plugins were enabled while reproducing the issue to write this.

Locking KeeAgent, then locking the KeePass Workspace, then unlocking the KeePass Workspace results in the following error:
Image:
![keeagent error](https://cloud.githubusercontent.com/assets/2312275/6987842/c2900dde-da19-11e4-84ef-b68e2f38c20e.png)

Content:
```
---------------------------
KeePass
---------------------------
KeeAgent: Error while loading key from entry 'General\SSH\id_rsa_rosemary'



Unexpected error



dlech.SshAgentLib.AgentLockedException: Exception of type 'dlech.SshAgentLib.AgentLockedException' was thrown.

   at dlech.SshAgentLib.Agent.AddKey(ISshKey key)

   at KeeAgent.KeeAgentExt.AddEntry(PwEntry entry, ICollection`1 constraints)
---------------------------
OK   
---------------------------
```

Pressing OK or closing the dialog results in the following prompt:

Image:
![keeagent prompt](https://cloud.githubusercontent.com/assets/2312275/6987899/1eb55344-da1a-11e4-8761-89dc26d607b6.png)

Content:
```
---------------------------
KeePass
---------------------------
Do you want to attempt to load additional keys?
---------------------------
Yes   No   
---------------------------
```

Pressing Yes on the prompt dismisses it with no further errors.

Pressing No on this prompt results in another error message dialog coming up. This has the same error as the first, but the entry is different. Pressing OK on this dialog gives the same result as the first (a prompt to load additional keys). This occurs once for each entry/key in the KeePass database for which:
* KeeAgent use is allowed, and
* the "Add key to agent when database is opened/unlocked." option is checked.

I've tested and confirmed that both conditions are required and an error dialog coming up for an entry is independent of whether that key was loaded into KeeAgent prior to it being locked.

**Comment by dlech** [comment]
Thanks for the detailed information. I'll have a look at this and see if I can reproduce the bug.

The issue with the yes/no dialog is #100.

**Comment by dlech** [comment]
Both issue should be fixed now. Please give this a try: http://files.lechnology.com/keeagent/0.6.0.1/KeeAgent.plgx.zip

**Comment by chrahunt** [comment]
Confirmed. Thanks!
