### ISSUE TITLE
Does not send keys to Pageant since v0.6.1

### ISSUE THREAD

**Issue by joos2k** [dlech/KeeAgent#104]
I'm using KeeAgent in client mode to push my keys into Pageant (because in Pageant I have easy access to all my stored PuTTY sessions).

Since v0.6.1 the keys will not be automatically loaded into Pageant anymore. I have downgraded to v0.6.0, now it works fine again. Any idea, how I could debug this behavior?

Thanks :)

**Comment by dlech** [comment]
Looks like I forgot a null check [here](https://github.com/dlech/KeeAgent/commit/b5e6a257ba54b2138c73ade815c39da05cbe66c7#diff-9456b6ec015112b448fb1e6ef2a331f8R712). Version 0.6.2 coming right up.

**Comment by dlech** [comment]
I've posted the new version on my website, so please try it and close this issue if it is fixed.

**Comment by joos2k** [comment]
Yes, it works. Thanks.
