### ISSUE TITLE
"Unexpected error" occurs when using KeeAgent in Client Mode with Pageant

### ISSUE THREAD

**Issue by insintesi** [dlech/KeeAgent#106]
Hi there,

I'm new to this, so apologies if my first post lacks the right title, format or amount of detail.

I have added a private SSH key to my KeePass file. Up until recently, it worked just fine. However, using KeePass 2.29 and KeeAgent 0.6.2, this error occurs:

>KeeAgent: Error while loading key from entry 'x/y/z'
>
>
>
>Unexpected error
>
>
>
>System.Exception: send message failed
>
>   bei dlech.SshAgentLib.PageantClient.SendMessage(Byte[] aMessage)
>
>   bei dlech.SshAgentLib.AgentClient.SendMessage(BlobBuilder aBuilder)
>
>   bei dlech.SshAgentLib.AgentClient.SendMessageAndCheckSuccess(BlobBuilder aBuilder)
>
>   bei dlech.SshAgentLib.AgentClient.AddKey(ISshKey key, ICollection`1 aConstraints)
>
>   bei dlech.SshAgentLib.AgentClient.AddKey(ISshKey key)
>
>   bei KeeAgent.KeeAgentExt.AddEntry(PwEntry entry, ICollection`1 constraints)

I have downgraded KeeAgent to both 0.6.0 and 0.6.1 without any success.

What does this error mean? What am I to do? Many thanks in advance for your help!

**Comment by dlech** [comment]
The error means that KeeAgent was not able to send a `WM_COPYDATA` message to Pageant window.

When does the error occur? Is Pageant running? Have you upgraded to PuTTY/Pageant 0.64 recently? Does this happen if you create a new key?

Looking at the [code](https://github.com/dlech/SshAgentLib/blob/master/SshAgentLib/PageantClient.cs#L83), I am sending the GC handle of the managed data instead of marshaling it to unmanaged, which does not make sense, so there is probably a bug here.

**Comment by dlech** [comment]
I've fixed the bug I spotted. Try [this](http://files.lechnology.com/keeagent/0.6.2.1/KeeAgent.plgx) and see if it fixes the problem, otherwise I will need some more information.

**Comment by bilbob74** [comment]
im not the initiator of this issue, but have the same problem. Here your fixed Version works. Many thx.

**Comment by insintesi** [comment]
It does fix it. Thank you very much!

**Comment by dlech** [comment]
Great. Makes me wonder how it ever worked. .NET must have changed its implementation of GCHandles recently. I've just release v0.6.3 that includes this fix.

**Comment by insintesi** [comment]
To my own surprise, this problem exists again. I have the latest versions of either KeePass and KeeAgent installed. Very peculiar!

**Comment by dlech** [comment]
Same stack trace in the error message?

**Comment by insintesi** [comment]
Yes, that's correct. And here's the funniest thing: As of now, it works again just fine. I've had this problem for the last five (obviously busy) days.
