### ISSUE TITLE
History of fetched keys (question)

### ISSUE THREAD

**Issue by Nihim** [dlech/KeeAgent#107]
It's not an issue but I couldn't find a better way.

When a program tries to access a key that keeagent has loaded in the manager it shows a pop-up with (something like): A program has requested key XX. Allow: Yes / No

Is there a way to see a history of which programs accessed each key?
If that is possible (no idea if keeagent sees which program is trying to access it) could it be added on the pop up too?

Cheers

**Comment by dlech** [comment]
> Is there a way to see a history of which programs accessed each key?

No, this information is not logged.

> could it be added on the pop up too?

This is issue #59.

**Comment by Nihim** [comment]
Hmm I have to agree that even only for windows it would be nice to show that kind of info, as it is important enough. Anyway closing this since my questions was covered by your reply & #59 

Cheers
