### ISSUE TITLE
Loaded key list reverted after database is closed/reopened

### ISSUE THREAD

**Issue by numericOverflow** [dlech/KeeAgent#108]
I have noticed that KeeAgent forgets what keys should be loaded whenever I open the app.  In a previous version, I had about 8 keys loaded before upgrading.  If I go into the KeeAgent screen and remove all but 5 of them, the new set of keys stays correct for the session, but will eventually revert to the "full" set of 8 keys the next time I close/open the database.  

I share the database across multiple computers, so I'm not sure if that's causing issues.  Where exactly do you store the list of keys to be loaded into memory?  Where ever it's being stored, the list seems to be discarded and I can't seem to get it to store/update with my new subset of keys.

I'm more than willing to help you diagnose or give you more details on what's happening.  Just let me know what details would help.

I'm running KP v2.29 with KeeAgent 0.6.3 on Win7x64 machines.

**Comment by dlech** [comment]
The settings for loading keys automatically when opening (or unlocking) a database are stored in each individual entry. See <http://lechnology.com/software/keeagent/usage/options-and-settings/#entry-settings>. It sounds like you are manually unloading the key using the KeeAgent manager which does indeed only affect the current "session" and is not remembered when KeePass is closed.

**Comment by dlech** [comment]
Closing due to no response. Please re-open if this is not just a configuration problem.
