### ISSUE TITLE
Can't use ed25519 keys on linux

### ISSUE THREAD

**Issue by grazzolini** [dlech/KeeAgent#112]
I'm using KeeAgent beta 7.1.2 on linux and I'm not able to use ed25519 keys. I've generated a ed25519 key, created an entry for it on KeePass, and I'm configuring KeeAgent to use it, but it throws the error in the attached imaged when trying to insert the key into the agent:
![ed25519](https://cloud.githubusercontent.com/assets/4093184/8625711/db46524e-2716-11e5-9007-8e5390a7aa1a.png)

This error happens with both an attached file, and also when pointing KeeAgent to the location of the file. I've even tried to create a key with no passphrase, and it still didn't worked.

**Comment by dlech** [comment]
Thanks for reporting. Looks like I missed adding some code to make Ed25519 keys work in client mode. This should be fixed in v0.7.3. You can download it from <http://lechnology.com/software/keeagent/> or it will be available via ppa shortly.

**Comment by grazzolini** [comment]
Thank you very much for your prompt response. I'm maintaining packages for Archlinux for both the stable and beta versions of KeeAgent. It's an indispensable tool for any admin to keep their ssh keys secure while resting on the disk(in case of using with an external file), while making it in a very convenient and secure way.
