### ISSUE TITLE
Option to ignore non-found keys during autoloading

### ISSUE THREAD

**Issue by LeoVerto** [dlech/KeeAgent#113]
I use the same KeePass db on multiple devices and thus have different keys on each of them.
However I'd still like for KeeAgent to automatically load these keys, currently this kind of works but one has to click away all the errors every time the db is loaded.

I thought about this for a bit and came up with two solutions: Either a per-device setting for key loading, which would be a lot harder to set up since KeePass (afaik) doesn't have any per-device settings, or alternatively **an option to simply ignore "File not found" errors when loading keys on KeePass startup.**

I think it would make more sense to do this only for that one kind of error so users still get notified when something else goes wrong.

This could either be done per-entry or globally, my opinion is that globally would make more sense as someone who needs this would probably enable it for most keys anyways.

**Comment by dlech** [comment]
Just to be clear, your keys are stored externally to the database and not as attachments?

**Comment by LeoVerto** [comment]
Yes, the keys are stored on a per-machine basis and not synced.

**Comment by KuttKatrea** [comment]
I second this enhancement, I need to have the keys in its own machines and only keep around the passphrases in KeePass

**Comment by dlech** [comment]
Fixed in b0eed2687ee74add4d10bfc6988bdd890487888e
