### ISSUE TITLE
Question: What happens if there are multiple valid keys?

### ISSUE THREAD

**Issue by sbrl** [dlech/KeeAgent#115]
I have my KeePass database synced via Dropbox, and I want to use it along with KeeAgent to store my ssh keys.

I also want to use a different for each machine, so I was wondering whether KeeAgent asks which valid key it should use if there is more than one valid key that it could use?

**Comment by dlech** [comment]
There is a feature in the latest beta version that lets you choose which key to use when a client program requests a list of keys. This option is disabled by default.

**Comment by sbrl** [comment]
Cool, thanks! How do I enable it?

**Comment by dlech** [comment]
On the KeeAgent tab under Tools > Options.

**Comment by sbrl** [comment]
Thanks! Found it :D

It's the "Show key selection dialogue..." option right?

**Comment by dlech** [comment]
Yes, that's the one.
