### ISSUE TITLE
Need better error message when KeeAgent is running in client mode and agent is closed.

### ISSUE THREAD

**Issue by mrjester888** [dlech/KeeAgent#116]
Got this error when trying to load a key into the agent.  Using 7.5 beta and KP 2.30. reverting to KA 0.6.3 resolved the problem.

![image](https://cloud.githubusercontent.com/assets/5603366/9430845/62abc76a-49b7-11e5-89d8-64b0ad671a67.png)

**Comment by dlech** [comment]
On Windows?

When you open the KeeAgent manager, what does it say in the title bar (Agent mode or Client mode)?

Are you running Pageant?

Do you have two copies of KeePass running at the same time?

**Comment by mrjester888** [comment]
Yes, Windows10.  I just tried to replicate the issue, but could not.   Not sure what mode it was in.  I had closed pagent and I am 99% sure I was not running two copies of KP.  

Unfortunately, I will just have to close this as probably something I messed up.

**Comment by dlech** [comment]
It could be that you started KeePass while Pagent was running and then closed Pagent while KeePass was still running. This would be the expected error in this case - although it could use a more clear error message.

**Comment by ubnt-bane** [comment]
That is actually what occurred.  I do remember closing Pagent after KP we started.  Yes, I better error message would be helpful.  Nice deduction.

**Comment by dlech** [comment]
OK. I'm going to reopen the issue for a better error message.

**Comment by dlech** [comment]
Fix is released in v0.7.6.

http://lechnology.com/2015/09/keeagent-beta-v0-7-6-released/
