### ISSUE TITLE
Cannot open keyfile

### ISSUE THREAD

**Issue by call-a3** [dlech/KeeAgent#117]
I followed the guide to add an SSH key to KeePass so that KeeAgent can access it. However, every time KeePass starts I get an error message saying

```
KeeAgent: Error while loading key from entry 'AdriaanCallaerts\Private SSH Key'

Could not load file from attachment 'MyKeyFile.ppk'

Possible causes:

- Passphrase was entered incorrectly

- File is corrupt or has been tampered
```

However, I've never even been given the possibility to enter my passphrase (and haven't found anywhere in the UI where I might enter one). I know the file isn't corrupt because it works just fine when I use it with PuTTY directly.

The same thing happens when I use the OpenSSH-formatted id_rsa file that contains the same key and with another SSH key that I use for business (both PuTTY and OpenSSH formats)

**Comment by dlech** [comment]
The passphrase goes in the password field of the KeePass entry.

**Comment by call-a3** [comment]
It's the strangest thing, I thought I tried that already... However, because you responded, I tried (again?) and now it seems to work just fine... Maybe my mind is playing tricks on me...

Anyway, thanks for the helpful and fast response!

**Comment by dlech** [comment]
Glad it's working. :smile:
