### ISSUE TITLE
Disabling SSH component Debian 8 "Jessie" (Gnome 3.14.1)

### ISSUE THREAD

**Issue by zeorin** [dlech/KeeAgent#118]
The instructions at http://lechnology.com/software/keeagent/installation/#disable-ssh-component-of-gnome-keyring are out of date for the latest version of Debian stable.

Gnome 3.14.1 no longer has a startup applications option in settings. This configuration is now only available via the `gnome-tweak-tool` application. Unfortunately, this tool only shows user-level startup scripts (i.e. those in `~/.config/autostart/`), even when `NoDisplay=false` is set in `/etc/xdg/autostart/gnome-keyring-ssh.desktop`.

To get it to work, I copied `/etc/xdg/autostart/gnome-keyring-ssh.desktop` to `~/.config/autostart/gnome-keyring-ssh.desktop`, and added the line `X-GNOME-Autostart-enabled=false`.

**Comment by dlech** [comment]
Geez, they don't make it easy do they? I will update my website accordingly.

**Comment by dlech** [comment]
I tried very hard today to make these changes, but for some reason my website refuses to let me have `/etc/` anywhere on the page. :angry:

Hopefully I can get this fixed soon.

**Comment by dlech** [comment]
done.
