### ISSUE TITLE
Having two places to enable confirm constraint is confusing.

### ISSUE THREAD

**Issue by olegstepura** [dlech/KeeAgent#122]
If I unselect "Use confirm constraint" KeeAgent still shows a confirmation popup. 

KeeAgent 0.6.3.0 on KeePass 2.30

**Comment by dlech** [comment]
There are several places where there is a "Use confirm constraint" checkbox. Do you mean the one in the [password entry settings](http://lechnology.com/software/keeagent/usage/options-and-settings/#entry-settings)? 

Also, make sure you don't have the global confirm constraint enabled in the main [KeePass options](http://lechnology.com/software/keeagent/usage/options-and-settings/#global-options).

**Comment by olegstepura** [comment]
Hi! I was talking about password entry settings, but yes, globally it was on.
It's confusing to have two similar options that conflict this way.

Anyways if you don't think so, please close this. But I suppose new users (as I am) could have same experience.

**Comment by dlech** [comment]
I suppose I could add an indicator of some sort on the entry settings that reminds you that the global option is on.

**Comment by olegstepura** [comment]
:+1:

**Comment by nifr** [comment]
:+1:

**Comment by dlech** [comment]
Fix has been released in KeeAgent v0.7.12. Please [download](http://lechnology.com/software/keeagent/#download) and try it out.

**Comment by olegstepura** [comment]
I see a read-only "global confirm enabled" label instead of a checkbox if I enable global confirmation. Everything seem to be ok.

:+1:
