### ISSUE TITLE
Cannot find passphrase with field reference

### ISSUE THREAD

**Issue by crazy-max** [dlech/KeeAgent#124]
Hi,

My passphrase is not resolved through the field reference option.
When i add the plain password it works.

Thanks

**Comment by dlech** [comment]
What version of KeeAgent are you using?

Are you seeing the same error message #94? This sounds like the same issue.

**Comment by crazy-max** [comment]
It seems to be the smae issue yes.
I am on KeeAgent 0.6.3

**Comment by dlech** [comment]
Try the beta release. It should be fixed.

**Comment by crazy-max** [comment]
Yes works on 0.7.8 thanks!

**Comment by dlech** [comment]
:thumbsup:
