### ISSUE TITLE
Using Confirm Constraint in Agent mode on Linux does not work.

### ISSUE THREAD

**Issue by dlech** [dlech/KeeAgent#127]
From @taurus-forever in #103

> 1) I have an error on loading module:
> ```
> ---------------------------
> KeePass
> ---------------------------
> KeeAgent: Error while loading key from entry 'bla/bla/some key'
> 
> Unexpected error
> 
> dlech.SshAgentLib.CallbackNullException: Exception of type 'dlech.SshAgentLib.CallbackNullException' was thrown.
>   at dlech.SshAgentLib.Agent.AddKey (ISshKey key) [0x00000] in <filename unknown>:0 
>   at KeeAgent.KeeAgentExt.AddEntry (KeePassLib.PwEntry entry, ICollection`1 constraints) [0x00000] in <filename unknown>:0 
> ---------------------------
> OK   
> ---------------------------
> ```
> It happens as soon as I enable option "Always require manual confirmation when a client program requests to use a key".

**Comment by dlech** [comment]
This is fixed in v0.7.9.

**Comment by taurus-forever** [comment]
Installed 0.7.9, it is proper/expected result?

Client/Auto mode:
```
---------------------------
KeePass
---------------------------
KeeAgent: Error while loading key from entry 'bla/bla/some key'

Agent Failure

Possible causes:

- Key is already loaded in agent

- Agent is locked
---------------------------
OK   
---------------------------
```

Agent Mode:
```
---------------------------
KeePass
---------------------------
Failed to start Unix Agent: Access denied
---------------------------
OK   
---------------------------
```
KeePass 2.30.

**Comment by dlech** [comment]
Was this before or after your comments in #103? If you are still seeing "KeeAgent: Error while loading key from entry..." or "Failed to start Unix Agent: Access denied", please open a new issue.

**Comment by taurus-forever** [comment]
It was a comment before #103.
At the moment it works well, thank you!
