### ISSUE TITLE
Instructions for disabling GNOME Keyring don't work on Linux Mint 17.2

### ISSUE THREAD

**Issue by dlech** [dlech/KeeAgent#128]
From @taurus-forever on #103:

> I did double check GNOME Keyring "issue", unfortunately the manual you created http://lechnology.com/software/keeagent/installation/#disable-ssh-component-of-gnome-keyring is no longer valid for Linux Mint 17.2. There are no "SSH Key Agent" in "Startup application", it doesn't appears after "NoDisplay=false". I have manually copied the /etc/xdg/autostart/gnome-keyring-ssh.desktop file to ~/.config/autostart/gnome-keyring-ssh.desktop, and edited, but had no luck.

**Comment by penetal** [comment]
Have you tried to just delete the file from /etc/xdg/autostart ?

**Comment by taurus-forever** [comment]
@penetal no, I did not try to delete /etc/xdg/autostart/gnome-keyring-ssh.desktop
Also it will be probably restored with next version of package gnome-keyring.

**Comment by aairey** [comment]
With me on Fedora 23 it used to work with Gnome Keyring, but now I changed my password for the keyring it stopped working ...

**Comment by dlech** [comment]
outdated
