### ISSUE TITLE
Using XDG_RUNTIME_DIR environment variable does not work for Agent mode on Linux

### ISSUE THREAD

**Issue by dlech** [dlech/KeeAgent#129]
from @taurus-forever on #103:

> The only solution which works for me is to specify full path in KeePass/Mono instead of "%XDG_RUNTIME_DIR%/keeagent.socket". Now, it works like a charm! Tnx!

**Comment by dlech** [comment]
Was able to duplicate this. Resulted in error "Access Denied" when starting KeePass. Environment variables were not being properly expanded.

**Comment by dlech** [comment]
This is fixed in Beta v0.7.10.

**Comment by taurus-forever** [comment]
The fix confirmed.
