### ISSUE TITLE
[enhancement] automatic identity-key selection

### ISSUE THREAD

**Issue by r2evans** [dlech/KeeAgent#131]
Dave,

You provide in your [Tips and Tricks](http://lechnology.com/software/keeagent/usage/tips-and-tricks/) page the option to do URL overriding. I'm inferring that it's to work around (among other things) the fact that some SSH daemons will fail with "too many authentication failures" for trying too many keys.

Does KeeAgent know enough about the connection (e.g., remote host, remote user) to determine (or infer) one "identity" for choice of certificate(s)? Either or both could be tied to something else in the KeePass entry (e.g., user name). The `{KEEAGENT:IDENTFILEOPT}` is close but unfortunately (1) doesn't work with `ssh` in existing terminals, (2) doesn't work with agent-forwarding, and (3) doesn't work with `scp` and `rsync`.

I looked at SSH-Agent API and couldn't find a definitive answer. Then again, I didn't quite follow a large amount of it, so it's likely that I missed something.

Thanks!

**Comment by dlech** [comment]
Unfortunately, the SSH agent protocol provides no information at all about what you are connecting to. I had to do some serious hacks to be able to find what process is even is trying to connect to it. We could probably do some more serious hacks to find about more about each process, but each application would have to be a special case, which sounds like a lot of work.

There is one thing you can do now though. You can use the `-i` option of `ssh`. To use this, you have to save your private key outside of KeePass. KeeAgent can do this for you automatically by using the "Save attachment to temporary file when key is loaded" option.

**Comment by r2evans** [comment]
That's exactly what I thought (and feared). I know about the `-i` option of `ssh`, though I'd have to put the `id_rsa` files on the filesystem; I was hoping to keep them completely within KeePass/KeeAgent. Thanks for the quick reply, I suspected it was a well-established "missing feature" (in the ssh agent protocol, in my eyes).

On a brighter note, it looks like OpenSSH-7.2 [will support something like this](https://bugzilla.mindrot.org/show_bug.cgi?id=2436): they will be overloading `-i ...` and `-o CertificateFile=...` so that, if not a file, then it must be a certificate label to be used. In that case, will KeeAgent automatically benefit from the improvement?

**Comment by dlech** [comment]
You could use a [ramdisk](http://www.howtogeek.com/171432/ram-disks-explained-what-they-are-and-why-you-probably-shouldnt-use-one/), then the key would never actually be on a physical disk.

I think the certificates patch that you pointed to will only be of use if your server supports certificates. Also, KeeAgent does not support certificates at this time.

**Comment by r2evans** [comment]
Thanks, I thought it'd transfer over. Poop. Still, I use this (and KeeFox/KeePassRPC) soooo many times a day, thanks! I'm a frequent evangelist of their use.
