### ISSUE TITLE
Use arrows to move up and down through possible keys

### ISSUE THREAD

**Issue by addshore** [dlech/KeeAgent#132]
As can be seen below the top key is selected in the key selection dialogue

![image](https://cloud.githubusercontent.com/assets/3308769/11427349/6607bdd8-9462-11e5-92b4-64f58ec8fe04.png)

From this point I would love to be able to hit the down key twice and then hit enter to use the bottom of the 3 keys.

Currently this is not possible as "Select" button is actually selected!

**Comment by dlech** [comment]
Sounds like a good idea. The list should be focused first, not the select button.

**Comment by addshore** [comment]
Awesome :)

**Comment by nifr** [comment]
+1

**Comment by dlech** [comment]
Fix has been released in KeeAgent v0.7.12. Please [download](http://lechnology.com/software/keeagent/#download) and try it out.

**Comment by addshore** [comment]
Seems to work! :D
Thanks!!!
