### ISSUE TITLE
new version not at your ppa

### ISSUE THREAD

**Issue by dkebler** [dlech/KeeAgent#134]
been a few weeks and that keepass keeps reporting a new version of keeagent available 6.3  but your ppa still has 6.2.  Do you wait to update the ppa with new releases?

**Comment by dlech** [comment]
As per the changelog, [the change in v6.3](https://github.com/dlech/KeeAgent/blob/v0.6.3/CHANGELOG.txt#L3) affects Windows only, which is why I did not bother updating the ppa.
