### ISSUE TITLE
ssh certificate authority (signed keys) support

### ISSUE THREAD

**Issue by sixspot** [dlech/KeeAgent#137]
Support for openssh certificate authority signed user keys (*-cert.pub) would be a wonderful addition. 
Below is an example with ssh-add and ssh-agent. (ed25519 keys are working fine with the KA beta.)

```
six@spot:~/.ssh/keys$ ls -l id_ed25519_150823*
-r-------- 1 six six  464 Jan 18 10:28 id_ed25519_150823
-r-------- 1 six six 1211 Jan 18 10:29 id_ed25519_150823-cert.pub
-r-------- 1 six six  102 Jan 18 10:28 id_ed25519_150823.pub
six@spot:~/.ssh/keys$ ssh-add id_ed25519_150823
Enter passphrase for id_ed25519_150823: 
Identity added: id_ed25519_150823 (id_ed25519_150823)
Certificate added: id_ed25519_150823-cert.pub (user_six)
six@spot:~/.ssh/keys$ ssh-add -l
256 SHA256:naHaEbpU5fQ5aRpe7BqBnouFi7MOH8RQy+voLokY7ok id_ed25519_150823 (ED25519)
256 SHA256:naHaEbpU5fQ5aRpe7BqBnouFi7MOH8RQy+voLokY7ok id_ed25519_150823 (ED25519-CERT)
```

**Comment by dlech** [comment]
I'll certainly consider it. If you have any links on how to setup this type of key/cert, it would be helpful.

**Comment by sixspot** [comment]
http://linux-audit.com/granting-temporary-access-to-servers-using-signed-ssh-keys/
https://chandanduttachowdhury.wordpress.com/2014/12/31/certificate-based-ssh-user-authentication/

Here's a brief example of a non-root setup:

# create user_ca and user_ca.pub, root not required, optional passphrase
```$ ssh-keygen -f user_ca```

# get a public key from the user and sign it
  ```$ ssh-keygen -s user_ca -I user_six -n six -V +1w id_ed25519.pub```

# send the signed key (id_ed25519-cert.pub) back to the user. place it alongside the original.

# add the user_ca.pub to ~/.ssh/authorized_keys on the server
  ```cert-authority <actual content of user_ca.pub goes here>```

**Comment by dlech** [comment]
Fix has been released in v0.9.1. http://lechnology.com/2017/03/keeagent-beta-0-9-1-released/

**Comment by deanslaunwhite** [comment]
Does the partial support you mention work on Windows 10?  If so, are there any instructions on how to get this working?  Apologies if they're already online somewhere, but I couldn't find them if so.

**Comment by dlech** [comment]
It probably doesn't work on Win10 at this point in time.

**Comment by dlech** [comment]
support for certificates is added in https://github.com/dlech/KeeAgent/releases/tag/v0.13.1
