### ISSUE TITLE
Conflicting Shortcut Defined: Ctrl + K to Load SSH Key and Duplicate Entries

### ISSUE THREAD

**Issue by turdbutt** [dlech/KeeAgent#138]
Howdy,

First, thank you for developing this plugin.

Second, I apologize if this is already known or if there's an obvious workaround but my brief research concluded there was not.

Ctrl + K is already defined in KeePass to duplicate entries, but when I right click and open the context menu, it shows that it's also defined to load an SSH key using your plugin. Shortcuts are awesome, but since yours conflicts with the pre-defined one, now neither will work.

Is it possible to re-define either of these shortcuts?

Screenshot:
![dup-shortcut](https://cloud.githubusercontent.com/assets/11865017/12951691/8f594336-cfe1-11e5-9318-71bae703ba30.JPG)

Cheers

**Comment by dlech** [comment]
Thanks for pointing this out. The shortcut for Duplicate Entry must be relatively new in KeePass since this used to work. Also since Duplicate Entry is a built-in feature of KeePass, I guess that mean that the KeeAgent one needs to change.

**Comment by turdbutt** [comment]
While you're changing keyboard shortcuts, would you consider adding a remove (all) keys button/shortcut?

**Comment by dlech** [comment]
Fix has been released in KeeAgent v0.7.12. Please [download](http://lechnology.com/software/keeagent/#download) and try it out.

Keyboard shortcut has been changed to CTRL+L.

**Comment by turdbutt** [comment]
Duplicating entries and loading PPKs now both work using keyboard shortcuts. Thanks!

My only criticism is that I don't see any confirmation if the key load was successful or not. 
I have to verify it manually by opening Tools > KeeAgent and inspecting the Manage KeeAgent window.

**Comment by dlech** [comment]
You can add a column to show the status of each entry. View (Menu) > Configure Columns... > Provided by Plugins (end of the list) > SSH Key Status
