### ISSUE TITLE
Linux: KeeAgent gets 'stuck' and wont provide keys

### ISSUE THREAD

**Issue by Icerius** [dlech/KeeAgent#142]
I am running Keepass with KeeAgent 0.7.11 under mono on Arch Linux in agent mode and I seem to be having a similar problem to #109 

First usage of the agent works but subsequent usage of the agent hangs until the first client exits.

**Comment by dlech** [comment]
What client (and client version) are you using? #109 was for Windows, but we probably need to make the same sort of change for Linux.

**Comment by Icerius** [comment]
I am running KeePass 2.32 installed from the standard community repo on Arch Linux. KeeAgent 0.7.11 is installed using the keepass-plugin-keeagent-beta package in AUR.

**Comment by dlech** [comment]
I meant the ssh client. Is is it the `ssh` command from OpenSSH?

**Comment by Icerius** [comment]
No problems. I am using the ssh command from OpenSSH and I am also using pam_ssh_agent_auth for sudo authentication through ssh-agent.

**Comment by Icerius** [comment]
OpenSSH is the latest version in Arch: 7.2p2

**Comment by dlech** [comment]
Fix has been released in KeeAgent v0.7.12. Please [download](http://lechnology.com/software/keeagent/#download) and try it out.
