### ISSUE TITLE
IOException: Cannot create file that already exists

### ISSUE THREAD

**Issue by Jonny007-MKD** [dlech/KeeAgent#147]
Hi,

I'm using KeePass 2.32 and 

Today I installed the KeeAgent plugin on a new machine. Everything worked as expected.
Now after the first database lock, I get this error when trying to load a key:

 > KeeAgent: Error while loading key from entry 'putty key'
 > 
 > Unexpected error
 > 
 > System.IO.IOException: Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist. (File already exists)
 > 
 > System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
 > ...
 > System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(...)
 > dlech.SshAgentLib.PageantClient.SendMessage(byte[] aMessage)
 > dlech.SshAgentLib.AgentClient.SendMessage(BlobBuilder aBuilder)
 > dlech.SshAgentLib.AgentClient.AddKey(ISshKey key, ICollection aConstraints)
 > KeeAgent.KeeAgentExt.AddEntry(PwEntry entry, ICollection constraints)

How can I delete this memory mapped file without restarting?

**Comment by dlech** [comment]
What version of KeeAgent are you using?

The memory mapped file is not a real file, so it can't be deleted as such. The only way you could get this error is if there were two connections at the same time with the same thread id. You will have to give more information about your exact setup to be able to reproduce the problem.

**Comment by Jonny007-MKD** [comment]
Oh sorry, I wanted to add this information after I copied the expection :) The KeeAgent version is `0.7.12`.

I only have KeeAgent running in KeePass, no other pageant. A reboot solved the issue, but still it's weird.

**Comment by dlech** [comment]
The stack trace shows that KeeAgent was running in client mode, but you said you were running "no other pageant", so KeeAgent should have been running in Agent mode. Perhaps there was a second instance of KeePass running that did not close properly or something.

It does not sound like there is anything to fix here, so closing the issue.

**Comment by Jonny007-MKD** [comment]
Mhm, sounds legit. But I updated KeePass from 2.24 to 2.32 after I got this error and it didn't go away. So something else must have been forcing KeeAgent to run in client mode. Thank you anyways!
