### ISSUE TITLE
Environment variables are not evaluated in Entry Settings when using an External Path for Private Key File Location 

### ISSUE THREAD

**Issue by KuttKatrea** [dlech/KeeAgent#148]
In the [Entry settings](http://lechnology.com/software/keeagent/usage/options-and-settings/#entry-settings) help page says that "For portable installations, you can use relative path names and/or environment variables.".

Relative names kind of works (it's not documented relative to **what**, testing it seems to be relative to $HOME (or %USERPROFILE%) directory in an installed KeePass, and to KeePass directory in case of a portable KeePass)

But environment variables are not evaluated in any way.

**Comment by dlech** [comment]
What version of KeeAgent are you using? What environment variable(s) did you try?

**Comment by dlech** [comment]
Fix has been released in [KeeAgent 0.9.0](http://lechnology.com/2017/01/keeagent-beta-0-9-0-released/). Please test.

**Comment by rjt** [comment]
I have an %EnvironmentVariable%  that is not interpreted at all, resulting in "Could Not Find File" error.   
KeeAgent 0.10.1
KeePass 2.40
