### ISSUE TITLE
Attached keys files are loaded from hard disc

### ISSUE THREAD

**Issue by Kharnivore** [dlech/KeeAgent#149]
I attached a key file (e.g. x.ppk) to KeePass entries. In the next step I selected this key file in the KeeAgent tab. I also checked the option to save the key temporarely on the hard disc.
Next I used the following command:
cmd://putty -noagent {KEEAGENT:IDENTFILEOPT} {USERNAME}@server -P Port

This works, until I changed the keys path in the filesystem. After renaming the key I get the following error message from putty: 
"Unable to use key file "file location" (unable to open file)"

The key is not saved in C:\Users\x\AppData\Local\Temp\KeeAgent. If I run 
cmd://echo {KEEAGENT:IDENTFILEOPT} 
I get the error message:
Arguments: -i "file location" Das System kann die angegebene Datei nicht finden (The system can´t open the specified file)

System: Windows 8.1, KeePass 2.32 with KeeAgent 0.6.3
Any ideas why this happens? Any logs I should attach?

**Comment by dlech** [comment]
You can try with the latest beta version, currently 0.7.12. I don't think anything has changed that would affect this, but it would be good to try anyway. Otherwise I will try to reproduce the problem when I get a chance.

> After renaming the key

What did you rename? The attachment?

**Comment by Kharnivore** [comment]
I renamed the key file on the hard disc.

I attached the file key.ppk to an entry in KeePass and then opened it -> It worked
I renamed the file on the hard disk to key_x.ppk without changing anything in KeePass, and deleted all cached keys -> It didn´t work, I got the error messages as mentioned above.

I will try the beta on a weekend, when nobody is in the office.

**Comment by dlech** [comment]
Maybe I am not understanding correctly, but if you move the key file that was created by KeeAgent (copy of the attachment), then of course KeeAgent cannot find it because it has no way of knowing that you moved the file. `{KEEAGENT:IDENTFILEOPT}` requires having the copy of the attached file saved to the hard drive (this is a requirement of PuTTY or any other ssh program that uses the key and not KeeAgent).

**Comment by Kharnivore** [comment]
Let´s start from the beginning ;)

Currently, we have a folder that contains all key files.

In KeePass, the URL field of most SSH entries looks like this:
cmd://putty -noagent {USERNAME}@server -P Port -i "C:\keyfolder\key_a.ppk"

We want to change our filestructure but don´t want to waste too much time on updating all entries in KeePass. Ultimately, we want to do it once, and don´t start again next time we want to change the filestructure.

What I did:
1) Attach the file C:\keyfolder\key_a.ppk to an entry in KeePass
2) Go to the tab KeeAgent
2.1) Tick the box "Allow KeeAgent to use this entry"
2.2 Untick the boxes "Add key to agent when database is opened/unlocked" and "Remove key from agent when database is closed/locked"
2.3) Tick the box "Attachment", select the keyfile, tick the box "Save attachment to temporary file when key is loaded"
3) Change the URL of the entry to: 
cmd://putty -noagent {KEEAGENT:IDENTFILEOPT} {USERNAME}@server -P Port
4) Try it out -> Putty is opened, gets the key and opens the connection -> Fine
5) Rename the original key file on the hard disc "C:\keyfolder\key_a.ppk" to "C:\keyfolder\key_a1.ppk" to simulate what happens if we move the keys to a different folder
6) Go to Tools -> KeeAgent and use "Remove all"
7) Try it out -> I get the error message, that the key couldn´t be found in "C:\keyfolder\key_a.ppk"
8) Change the URL field to cmd://echo {KEEAGENT:IDENTFILEOPT} and run it. 
Output: Arguments: -i "C:\keyfolder\key_a.ppk" Das System kann die angegebene Datei nicht finden (The system can´t open the specified file)
9) Check "C:\Users\x\AppData\Local\Temp\KeeAgent" to see if a local copy of the attached key file is saved -> It´s not

This leads me to the conclusion, that keyfiles are still loaded from the original file on the harddrive, instead of creating a copy of the attached file in C:\Users\x\AppData\Local\Temp\KeeAgent and using this local copy to open a ssh connection.

Did I miss to tick a box somewhere in the options? Or is this behaviour expected?

Thanks for your support :)

**Comment by dlech** [comment]
OK, so it sounds like when you switch from using an external file to using an attachment in the entry settings, the change in the settings are not actually taking effect. Of course, this is not the expected behavior. I will try to reproduce when I get a chance.

**Comment by be9em0t** [comment]
This still exists in current version.

**Comment by dlech** [comment]
I am not able to reproduce this issue with the current master.
