### ISSUE TITLE
Next stable

### ISSUE THREAD

**Issue by szepeviktor** [dlech/KeeAgent#150]
Hello!

Do you plan to release v7 stable?
Or I should consider the latest v7 as stable?

**Comment by dlech** [comment]
The beta version is usually quite stable. I will probably be releasing the v0.7.12 as v0.8.0/stable within the next month or so if no new bugs come up. So you should definitely try it out now.

**Comment by szepeviktor** [comment]
Thank you.
Installed.

Could you add some *margin* to make in look like Tools / Options
and close on <kbd>Esc</kbd> key?

**Comment by dlech** [comment]
This sounds like two separate issues. Can you please open new issues for these? And provide more details about what you are suggesting - I can probably guess what you mean, but it is not entirely clear.
