### ISSUE TITLE
UI margin

### ISSUE THREAD

**Issue by szepeviktor** [dlech/KeeAgent#151]
Could you add some margin to make it look like Tools / Options?

![keepass](https://cloud.githubusercontent.com/assets/952007/14764061/3b8330e8-09aa-11e6-8281-4519a6ed1815.jpg)
![keeagent](https://cloud.githubusercontent.com/assets/952007/14764062/4119f802-09aa-11e6-8a45-452f3f6f49be.jpg)

**Comment by szepeviktor** [comment]
Do you have any kind of release notification? (e.g. email newsletter, blog post, RSS)

**Comment by dlech** [comment]
Yes, that is it.

**Comment by dlech** [comment]
Also, if you have update notifications enabled in KeePass, it will notify you.
