### ISSUE TITLE
keeagent not working on ubuntu Xenial

### ISSUE THREAD

**Issue by tchize** [dlech/KeeAgent#154]
KeeAgent plugin doesn't start on ubuntu Xenial. Whether you use the ubuntu provided keepass, you download and use the latest portable version of keepass of use older version of keepass result is the same, plugin doesn't load.

Note also that keeagent is not available for xenial in PPA repository, so you have to download an copy the plugin file

Steps to reproduce:
download keeagent zip, put the KeeAgent.plgx next to KeePass.exe, run keepass.exe, get a message "The following plugin is incompatible with the current KeePass version: /home/davidd/Applications/keepass/KeeAgent.plgx Have a look at the plugin's website for appropriate version"

Running with --debug give this message:
"Operation is not valid due to current state of the object. KeePass" followed by a stacktrace.
See captures.
This is a problem as this mean I lost access to most of my ssh servers after ubuntu upgrade :/
![screenshot from 2016-05-04 16-28-28](https://cloud.githubusercontent.com/assets/7933441/15017409/bd460fec-1215-11e6-8b2e-c2ec3f13f797.png)
![screenshot from 2016-05-04 16-25-38](https://cloud.githubusercontent.com/assets/7933441/15017408/bd433290-1215-11e6-9e19-8e536005d92d.png)

**Comment by dlech** [comment]
You are probably missing some dependencies. This is usually solved by `sudo apt-get install mono-complete`. Alternatively, you can use the latest beta from `ppa:dlech/keepass2-plugins-beta`.

**Comment by tchize** [comment]
indeed, apt-get install mono-complete solved issue
