### ISSUE TITLE
Can't handle ed25519 keys

### ISSUE THREAD

**Issue by chris42** [dlech/KeeAgent#156]
Hi there,

I tried to get Keeagent running with ed25519 keys, however I always get the error, that the key could not be loaded.
Just to make sure: Correct, that keeagent can't handle the ed25519keys?
Too look forward: Any idea when this might be added?

Regards
  Chris

**Comment by dlech** [comment]
Are you using the beta version (currently 0.7.12 or so)? It should be able to handle ed25519 keys. If not, please attach a sample key that fails and I will have a look.

**Comment by chris42** [comment]
Yes, sorry was on the normal release. Tested the Beta and it works. Thanks!
