### ISSUE TITLE
No builds for Ubuntu 16.04 XenialXerus in ppa:dlech/keepass2-plugins

### ISSUE THREAD

**Issue by nifr** [dlech/KeeAgent#158]
There are currently no keeagent package builds for Ubuntu 16.04 available in your ppa.

https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins/+packages?field.name_filter=keeagent&field.status_filter=&field.series_filter=xenial

keepasshttp and the ubuntu plugin are being built for Xenial though.

Could you please add keeagent builds for 16.04?

Thanks for your awesome work with keeagent.

**Comment by dlech** [comment]
For now, use the beta ppa. https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins-beta

I really need to do a stable release based on the current beta, but I have been to busy with other projects that it hasn't happened yet. And I don't really want to support 0.6.0 on xenial.

**Comment by nifr** [comment]
Thanks for the quick reply David - I actually forgot about the beta repo. 

I had no issues with keeagent beta 0.7.12 on 16.04 Xenial so far.
