### ISSUE TITLE
Allow overwrite of socket file on startup (Windows only?)

### ISSUE THREAD

**Issue by saxonww** [dlech/KeeAgent#160]
If keepass or my pc crashes for some reason (e.g. power outage), when I restart keepass I get an error about the socket file already existing. I have to go remove the file then restart keepass in order to get keeagent working again. This happens frequently enough that I wonder if it makes sense to have an option for overwriting the socket file on startup.

**Comment by dlech** [comment]
What version of KeeAgent are you using? I think I did something like this already in the beta version. See #92.

**Comment by saxonww** [comment]
v0.6.3. Sorry, I didn't think about the beta versions, so I didn't look through closed issues to see if this had been fixed already.

Is the 0.8.0 milestone up to date, i.e. those two UI issues are all that's left before 0.8.0 is released as stable?

**Comment by dlech** [comment]
Yes. I've been meaning to do this for a long time, but have not made the time to do it yet.

**Comment by dlech** [comment]
Have you confirmed that this is working? Also, I just release v0.8.0.

**Comment by saxonww** [comment]
Yes I have, just now in fact due to crash/restart. I think this is good to
close.
