### ISSUE TITLE
Previous version left in code

### ISSUE THREAD

**Issue by szepeviktor** [dlech/KeeAgent#163]
https://github.com/dlech/KeeAgent/blob/bd9de6dc2dbf8ab811e6538481f7b50e7972f023/KeeAgent/Properties/AssemblyInfo.cs#L53-L54

**Comment by dlech** [comment]
Oh dear. That is what happens when I get out of practice.

**Comment by szepeviktor** [comment]
Keyword is Release checklist.
For example in GitHub Wiki ....
