### ISSUE TITLE
Failed to get reply from Pageant

### ISSUE THREAD

**Issue by numericOverflow** [dlech/KeeAgent#164]
I have found I have issues where keeAgent seems to stop responding to requests for keys.  The issue seems intermittent.  For example, just now it worked when I started my PC, but stopped after a couple hours of serving keys OK.  When I try via Putty and check the event log, this is all I see.   Restarting Keepass doesn't seem to fix the issue.

Is there some way to get more debug info out of KeeAgent to track down the problem?

> 2016-08-01 16:01:37	Looking up host "mydomain.com"
> 2016-08-01 16:01:37	Connecting to 99.99.99.99 port 99
> 2016-08-01 16:01:37	Server version: SSH-2.0-5.39 FlowSsh: Bitvise SSH Server (WinSSHD) 6.47
> 2016-08-01 16:01:37	Using SSH protocol version 2
> 2016-08-01 16:01:37	We claim version: SSH-2.0-PuTTY_Release_0.67
> 2016-08-01 16:01:37	Doing Diffie-Hellman group exchange
> 2016-08-01 16:01:37	Doing Diffie-Hellman key exchange with hash SHA-256
> 2016-08-01 16:01:37	Host key fingerprint is:
> 2016-08-01 16:01:37	ssh-rsa 4096 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 2016-08-01 16:01:44	Initialised AES-256 SDCTR client->server encryption
> 2016-08-01 16:01:44	Initialised HMAC-SHA-256 client->server MAC algorithm
> 2016-08-01 16:01:44	Initialised AES-256 SDCTR server->client encryption
> 2016-08-01 16:01:44	Initialised HMAC-SHA-256 server->client MAC algorithm
> 2016-08-01 16:01:44	Pageant is running. Requesting keys.
> 2016-08-01 16:01:44	Failed to get reply from Pageant

I'm running Win7 (x64), Keepass v2.34, keeAgent v0.8.1.0 (though I've seen it happen on v0.7x as well).

**Comment by dlech** [comment]
Unfortunately, there isn't a way to get debug info from KeeAgent (other than running it using Visual Studio).

The fact that restarting KeePass does not fix the problem but restarting your computer does tells me that it has something to do with the memory mapped file that is used to transmit information between applications.

Unless there is a reliable way to reproduce this, I can't do much at the moment. I don't currently have the time to add debug logging.

**Comment by numericOverflow** [comment]
I did some experimenting yesterday.

**Background**:  My previous laptop exhibited these symptoms, I noticed it in the last 6 months or so (roughly), but never looked at it too hard so don't have any real metrics on it's occurrence frequency.  I recently (July 2016) got a new laptop and setup all my software.  I noticed the issue and finally decided to dig into it a bit. 

**Testing Setup**:  My laptop was exhibiting the "Pageant failed to reply" symptoms.  Had not rebooted and decided to experiment with some things to pin down exact symptoms and potential causes.

**Keepass setup**: I use triggers to kick off WinSSHFS to mount a remote drive via SSH/SCP.  When Keepass DB loads, there is a trigger action that starts WinSSHFS executable via "Execute cmd line/URL".  

**Experiment 1 - Validate Pageant works (independently when Keepagent fails) [SUCCESS]**
1) keepass closed, not running
2) Start Pageant.exe , load a ppk from locally stored file
3) Start WinSCP, open connection requiring an key
4) Pageant is contacted, replies and provides a key
5) This scenario works as expected.

> . 2016-08-02 09:00:21.103 Pageant is running. Requesting keys.
> . 2016-08-02 09:00:21.104 Pageant has 1 SSH-2 keys
> ! 2016-08-02 09:00:21.104 Using username "xxxxxxxxxxxxx".
> . 2016-08-02 09:00:21.111 Waiting for the server to continue with the initialization
> . 2016-08-02 09:00:21.144 Detected network event
> . 2016-08-02 09:00:21.145 Trying Pageant key #0
> . 2016-08-02 09:00:21.145 Waiting for the server to continue with the initialization


**Experiment 2 - KeeAgent as Client to Pageant (auto mode) [FAIL]**
A) Open Keepass
B) Open database with only 1 entry that has an attached key, set to auto-load key
C) Keeagent throws an error when trying to send key to Pageant:
D) Key doesn't load
![alt text](http://i.imgur.com/lKe6nGD.jpg "Keeagent errror")


**Experiment 3 - KeeAgent in agent mode [FAIL]**
A) Open Keepass
B) Keys attached to entries are auto-loaded to keeagent based on entry settings.
C) Check Keeagent window shows key loaded.
D) WinSSHFS (instance that was spawned by keepass thread) opens
E) Agent supplies WinSSHFS  with key, and SSH session connects OK.
D) --> Using the same process instance of WinSSHFS, I can disconnect/reconnect repeatedly and works OK (SSH key is fetched on each connection OK)
E) Kill the keepass-spawned instance of WinSSHFS (orignal keepass stays running)
F) Start another instance of WinSSHFS
G) Any/all requests from new, non-child process are not replied to by Keepagent.


**Experiment 4 - Validate that processes spawned by Keepass can communicate, non-child processes cannot. [PARTIAL SUCCESS]** 
A) Open Keepass
B) add additional trigger to spawn putty.exe process upon DB opening.
C) Restart Keepass
D) WinSSHFS & Putty.exe process get spawned by keepass
E) Keys attached to entries are auto-loaded to keeagent based on entry settings.
F) Check Keeagent window shows key loaded.
G) Agent supplies child process WinSSHFS  with key, and SSH session connects OK.
H) Agent supplies child process Putty.exe with key, and SSH session connects OK.
I) Kill the keepass-spawned instance of WinSSHFS (original keepass stays running)
J) Start another instance of WinSSHFS
K) Any/all requests from new, non-child process do not receive a reply from Keepagent.
L) Kill child process Putty.exe, restart as non-child and it is also denied like WinSSHFS
![alt text](http://i.imgur.com/Snoqr3O.jpg "Logo Title Text 1")

**Take-aways**
I'm not sure exactly why this is happening, but as a work-around, I've setup triggers within Keepass so that that process can spawn executables that depend on a key agent for authentication.  While it's a bit odd, it seems to work for now.  Maybe we could figure out exactly what is causing the communication blockage between Keepass/KeeAgent and the processes requesting keys.  It seems to have something to do with the mix of non-elevated and elevated privileges of the processes.

**Comment by dlech** [comment]
> It seems to have something to do with the mix of non-elevated and elevated privileges of the processes.

Can you explain more about this? Which processes are elevated and which are not? It is expected that an elevated process cannot communicate with a non-elevated process.

**Comment by numericOverflow** [comment]
Sorry, I somehow managed to delete experiment #5 while assembling the post ...

**Experiment 5 - Run both processes with elevated privileges [SUCCESS]**
A) Start Keepass (which I've set to run with elevated admin privileges but default)
B) Start Putty (right-click, run as Administrator)
C) Putty contacts KeeAgent which replies and provides a key
D) This scenario succeeds.

To answer your question: I'm inferring that since my baseline situation fails (Keepass always runs elevated, but processes requesting keys were not elevated), and experiment #5 succeeds (where both run elevated) work, the privilege elevation differences may be the smoking gun.  I don't know, but I'd think elevated & non-elevated processes *should* be able to communicate, but I don't know how exactly those security differences may play out.

FYI - I am running Keepass w/admin privileges by default because I also use KeepassHTTP which can't setup the communications port w/out admin privileges and therefore Chrome can't talk to Keepass via KeepassHTTP.

**Comment by dlech** [comment]
> I don't know, but I'd think elevated & non-elevated processes should be able to communicate,

No. This is essentially the same as running the two process as a different user. This is done for security, otherwise non-elevated processes could take over elevated processes.

I find it odd that KeePassHttp would require running with elevated privileges. Perhaps there is something in Windows Firewall (or other security software that may be installed) that will allow KeePassHttp to open a socket.

**Comment by numericOverflow** [comment]
> No. This is essentially the same as running the two process as a different user. This is done for security, otherwise non-elevated processes could take over elevated processes.

Ah, OK.  That makes sense, I've just never seen it cause problems like this.  To be fair, most times I've seen it communications have been port based, which seems to work fine.

> I find it odd that KeePassHttp would require running with elevated privileges. Perhaps there is something in Windows Firewall (or other security software that may be installed) that will allow KeePassHttp to open a socket.
 
Yes, it's a firewall/permissions restriction that doesn't allow non-admin processes to open & use a network port.

I guess we've uncovered the cause of the issue.  There's probably not much for you to do, just having my experience and workaround available to others if they experience a similar situation should be sufficient.
