### ISSUE TITLE
KeeAgent + SecureCRT

### ISSUE THREAD

**Issue by gruselglatz** [dlech/KeeAgent#167]
Hi,

is someone using KeeAgent with the Software SecureCRT, and could provide some help?

https://www.vandyke.com/products/securecrt/

Thanks

**Comment by dlech** [comment]
From the [looks of it](https://www.vandyke.com/support/tips/publickeyauth.html), the software don't use an agent for public keys. Probably the best you could do is use the KeeAgent feature to save a key to a file on disk when it is loaded and setup SecurCRT to read that file. Then use the AutoType feature of KeePass to type the passphrase in SecureCRT.

**Comment by gruselglatz** [comment]
Thank you. ;)

Do you know any good option, to delete the file after secureCRT opened a connection? I use the autotype to enter the passphrase of the key before the connection is opened.

**Comment by dlech** [comment]
The file should be deleted when the KeePass database is closed/locked.
