### ISSUE TITLE
ed25519 on Linux

### ISSUE THREAD

**Issue by strasharo** [dlech/KeeAgent#170]
Hello. I'm trying to use an ed25519 key with KeeAgent 0.8.1 and Keepass 2.34 on Linux. 
On KeeAgent tab everything seems to be fine:
![screenshot at 2016-09-25 16-47-20](https://cloud.githubusercontent.com/assets/3337997/18815633/cb5ed42e-833f-11e6-80ea-89873d4a27ee.png)
However when I try to load the key it throws the following error:
![screenshot at 2016-09-25 16-48-58](https://cloud.githubusercontent.com/assets/3337997/18815663/fa878e44-833f-11e6-948f-39a421c86e3b.png)
The agent is not locked and the key is not already added. All of my other RSA keys work well, I only have issues with the newly created ed25519 one.
The key was generated using the following args and a password was applied to it:
`ssh-keygen -o -a 100 -t ed25519`

**Comment by dlech** [comment]
This sounds like #169. I'll see if I can reproduce with an ed25519 key.

**Comment by strasharo** [comment]
Just tried generating the same key without a password and I got the same error. When I tried to load manually the key (which wasn't password protected) from the "Manage KeeAgent - Client Mode" dialog I got the following error:
![screenshot at 2016-09-25 17-27-48](https://cloud.githubusercontent.com/assets/3337997/18815878/696cf646-8345-11e6-97c2-3df69288da16.png)

**Comment by strasharo** [comment]
Just tested it on Windows with the same versions of the components and it works there. So I guess the issue is Linux specific.

**Comment by dlech** [comment]
Except that on Windows, you are using KeeAgent in Agent Mode and on Linux, you are using KeeAgent in Client Mode, correct?

**Comment by strasharo** [comment]
Yep, you're absolutely correct, it's set to auto and it's running in client mode. Initially I thought that it was in agent mode, because I didn't run any additional agent, but just noticed that Mate desktop was silently running an agent in the background and I wasn't even aware of it:
http://william.shallum.net/random-notes/disabling-gnome-keyring-daemon-ssh-agent-on-mate-desktop

Sorry for the false alarm. :)
