### ISSUE TITLE
ctrl+shift+l doesn't work correct of you load multiple keys

### ISSUE THREAD

**Issue by geki007** [dlech/KeeAgent#174]
i try to load and open 5 keys (putty sessions) with ctrl+shift+l
every item opens multiple times, no "load key" notification is shown ... i think something (win explorer?) crashes
i use win 10 x64
if i do the same with ctrl+l and then ctrl+u it works correct

**Comment by dlech** [comment]
Can you please provide more information about your complete configuration. How do you have keys configured in KeePass? What is the command that you have configured? Are you selecting all 5 keys at one time?

The more information you can give, the better chance I will have at reproducing the problem.

**Comment by geki007** [comment]
I will try
- yes, i select all 5 keys at one time and press the shortcut ... if i do it with 1 key it works
- URL overwrite: cmd://"C:\Program Files (x86)\PuTTY\PuTTY.exe" -load "..." -l "{USERNAME}"
- Have set "show a notification whenever a key is used ..."
- Agent mode auto but have no other agent so it's in agent mode
- 1 (other) key is automatically loaded to agent when database is loaded

Setting of the 5 keys
- Keys as attachment but not save as temporary file
- Unset "Add key to agent when database loaded"
- Set "remove key when database locked"
- Set "Use lifetime constraint ... 600"

**Comment by geki007** [comment]
Hi again,
didn't know if i should fill a new bug.
With 0.9 beta i have a new problem:

If i press ctrl+shift+m and have selected multiple entries they are opened multiple times.

- 1 selected -> opens 1 window
- 2 selected -> opens 2*2 windows
- 3 selected -> opens 3*3 windows

**Comment by dlech** [comment]
This sounds like basically the same problem, so no need to open a new issue.

**Comment by geki007** [comment]
Thanks for the fix
Hope will see new Release or Beta soon

**Comment by dlech** [comment]
Fix has been released in v0.9.1. http://lechnology.com/2017/03/keeagent-beta-0-9-1-released/

**Comment by geki007** [comment]
Looks fixed ... and thanks for the info

**Comment by dlech** [comment]
Thanks for confirming.
