### ISSUE TITLE
Cygwin socket

### ISSUE THREAD

**Issue by aairey** [dlech/KeeAgent#176]
Hello I want to use KeeAgent together with [babun](http://babun.github.io), it is basicly a cygwnin environment.

I'm creating this issue as it was mentioned here: https://github.com/babun/babun/issues/290

I have set KeeAgent to create a local socket file.
The file gets created but it holds 0 bytes.

When I try to use it by setting `SSH_AUTH_SOCK`, it fails to connect to the socket.
Any help would be appreciated.

**Comment by dlech** [comment]
What is the path where you are saving the socket file?

**Comment by aairey** [comment]
`C:\Users\me\.babun\home\me\keeagent.sock`

**Comment by dmak** [comment]
Actually socket works fine for me in Cygwin (OpenSSH 6.7). The only thing I needed is to `export SSH_AUTH_SOCK=/path/to/agent.sock`. Created socket is 53 bytes (if you view with Windows tools like Explorer or cmd). The only difficulty was to find out that SSH actually uses the key from the agent from `ssh -v` output.

**Comment by aairey** [comment]
I am still facing this issue, KeeAgent is still creating a socket file of 0 bytes.

Running KeePass as Administrator does not help either.

```
» ll c:/Users/aairey/keeagent.sock

srw-r--r-- 1 aairey aairey 0 Jan  4 22:34 c:/Users/aairey/keeagent.sock
» file c:/Users/aairey/keeagent.sock

c:/Users/aairey/keeagent.sock: socket
» tail c:/Users/aairey/keeagent.sock

tail: cannot open 'c:/Users/aairey/keeagent.sock' for reading: No such device or address
```

**Comment by dlech** [comment]
Based on `C:\Users\me\.babun\home\me\keeagent.sock`, I would expect the socket to be at `/home/me/keeagent.sock` inside of the babun environment, not at `c:/Users/aairey/keeagent.sock`.

**Comment by aairey** [comment]
Yes, I should have mentioned I tried a different path this time.

**Comment by r2evans** [comment]
@aairey, you mentioned that it created a socket file of 0 bytes. That's normal, I think. What file size are you expecting?

For perspective, this is working for me, using "Git for Windows" (currently 2.11.1), KeePass-2.35, KeeAgent-0.9.0.0:

- KeePass *Options > KeeAgent*, create cygwin compatible socket, path `c:\Users\r2\.ssh\ssh-agent.sock`
- Windows, *System Properties > Advanced > Environment Variables ...*, `SSH_AUTH_SOCK` is set to `c:\Users\r2\.ssh\ssh-agent.sock`

```bash
$ echo $SSH_AUTH_SOCK
C:\Users\r2\.ssh\ssh-agent.sock
$ ll ~/.ssh/ssh-agent.sock
srwx------ 1 r2 197121 0 Feb  6 10:04 /c/Users/r2/.ssh/ssh-agent.sock
```

**Comment by aairey** [comment]
It appears I really needed to add it to the end of my `.zshrc` file.
As the oh-my-zsh plugin `ssh-agent` would create a socket file in `/tmp` even though `SSH_AUTH_SOCK` is set ...

So fixed by adding this line to the bottom of my `.zshrc` (or anywhere after `source $ZSH/oh-my-zsh.sh`):
```
SSH_AUTH_SOCK="$HOME/keeagent.sock"
```
And placing my `keeagent.sock` file in C:\Users\andy\.babun\cygwin\home\andy\keeagent.sock`.
