### ISSUE TITLE
Incompatible plugin (compilation error) with Ubuntu

### ISSUE THREAD

**Issue by symera** [dlech/KeeAgent#177]
I get this error message while I am trying to run KeePass (in portable mode) with KeeAgent under Ubuntu (Mono):

```
The following plugin is incompatible with the current KeePass version:
path/to/KeeAgent.plgx
Have a look at the plugin's website for an appropriate version.
```
After running KeePass with the --debug option I got the following log file: [tmp5712597b.txt](https://github.com/dlech/KeeAgent/files/602561/tmp5712597b.txt)

**Comment by dlech** [comment]
The easy fix is

    sudo apt-get install mono-complete

If you are picky about only installing the packages you need, try

    sudo apt-get install libmono-system-data-datasetextensions4.0-cil

**Comment by symera** [comment]
Thanks for the quick reply and solution.

I tried
`sudo apt-get install libmono-system-data-datasetextensions4.0-cil`
and it did the job.

**Comment by r2evans** [comment]
@dlech, in case you happen to know ... the installation of `libmono-system-data-datasetextensions4.0-cil` is no longer sufficient, do you know of another package (or two) that need to be installed for plugin compilation? I'll be happy to open another issue if you'd prefer, and if you don't know then it isn't earth-shattering ... `mono-complete` solved it at the expense of my antipathy towards installation of many unused packages. Thank you!

**Comment by dlech** [comment]
> I'll be happy to open another issue if you'd prefer,

yes please.
