### ISSUE TITLE
Dialog window for key use confirmation should have focus

### ISSUE THREAD

**Issue by dev169** [dlech/KeeAgent#180]
I think this would be classed as a usability enhancement. 

When using confirm constraints, the dialog box that pops up does not have focus, so one needs to select it before interacting with it. If it had focus by default, one could simply visually inspect the details and simply use the keyboard to select Yes or No (Alt+Y or Alt+N). Now it requires reaching for the mouse, locating and clicking the dialog box and then clicking on the desired button. Breaks the flow when you are deep in the terminal.

Would this be possible?

**Comment by KuttKatrea** [comment]
I had contributed this enhancement on dlech/SshAgentLib#7, but it is not merged yet

**Comment by dlech** [comment]
Looks like I missed closing this issue. The fix was released in v0.9.0.
