### ISSUE TITLE
AddKeyToAgent seems to fail but occasionally works (Sort of)

### ISSUE THREAD

**Issue by xenithorb** [dlech/KeeAgent#181]
I was testing something out and needed the `AddKeyToAgent` feature to automate part of the process. I don't think this is working properly with KeeAgent in agent mode on linux. 

(Note: I prefer agent mode on Linux due to the automated password asking / and the fact that it doesn't leave files around) 

Config:
```
Host hyperion-vagrant
        Hostname 192.168.1.3
        ForwardAgent yes
        AddKeysToAgent yes
        IdentityFile ~/.ssh/insecure_private_key
        #IdentitiesOnly yes
        ControlMaster no
        ControlPath ''
```

So here's the interesting thing... Ideally what would happen is that `~/.ssh/insecure_private_key` is added to the agent, which if the connection succeeds it is not. 

The caveat here is that `insecure_private_key` in my setup is not meant for this host exactly, I just wanted to add it to the agent, and what I discovered is that if I add `IdentitiesOnly yes` which forces it to use that Identity, then obviously the connection fails, BUT, if I `ctrl+c` mid-connection failure, _it does add the key to the agent!_ Now that's a bit odd. 

Some relevant errors I saw in debug output: 

```
debug1: key_load_public: No such file or directory
debug1: identity file /home/xenith/.ssh/insecure_private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/xenith/.ssh/insecure_private_key-cert type -1
```

I assure you the file is there with the proper permissions, furthermore if I wait for the connection to time out (when I use `IdentitiesOnly yes`) it outputs the following:

```
debug1: could not add identity to agent: /home/xenith/.ssh/insecure_private_key (-27)
```
Again, if I `ctrl+c` before this message shows, it does in fact add it to KeeAgent listed as from an "External Client" 

To reiterate: The goal here is that the key should be added during a successful connection, and it is not. For whatever reason, the key is only added when you interrupt the connection process.

**Comment by xenithorb** [comment]
Additionally, `ssh-add` works fine, every time.

**Comment by xenithorb** [comment]
I think this has something to do with the differences in the way `ssh` adds keys to agents versus `ssh-add`. I'm using ssh version:

```
OpenSSH_7.3p1, OpenSSL 1.0.2j-fips  26 Sep 2016
```

**Comment by dlech** [comment]
I played around with this a bit and it has nothing to do with KeeAgent. If there is not a matching public key in `authorized_keys` on the server, then the key specified by `IdentityFile` will not be loaded into the agent. This is a bug/feature of OpenSSH.

**Comment by xenithorb** [comment]
Fair enough. I thought I had checked with `ssh-agent` prior to writing this but I can't remember and maybe I overlooked something. Thanks for checking it out
