### ISSUE TITLE
windows explorer freezing after a git push

### ISSUE THREAD

**Issue by r2evans** [dlech/KeeAgent#184]
I cannot reproduce this with other ssh key actions, just a `git push ...`. Each `git push` invokes two ssh connections, and since I ask for key-selection, I select the same key both times. After the first connection, windows explorer is still responsive. Immediately after the second key-use, much of the windows explorer functionality is locked up: I can still <kbd>Ctrl</kbd>-<kbd>Tab</kbd> (luckily), but things like <kbd>Win</kbd>-<kbd>1</kbd> (and other taskbar position numbers) do not work; the taskbar is unresponsive to mouse events; tray icons are not updating; etc. The workaround has been to kill windows explorer in the task manager (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>Escape</kbd>, select Explorer, <kbd>Alt</kbd>-<kbd>E</kbd>), and things start right back up, no other noticeable or lingering effects.

I tried different combinations of actions:

- other actions (e.g., `ssh`, `git pull`) do not cause the freeze
- doing `git push ...` not using KeeAgent does not cause the freeze
- doing `git push ...` using KeeAgent ***sometimes*** causes the freeze

The only qualifier I have on "sometimes" is larger pushes tend to freeze it, smaller ones tend not to. This *may* be a `git` problem (introduced middle/late in the 2.10 chain), but I've been testing repeatedly with "using KeeAgent" and "not using KeeAgent", and I have not yet caused a hang on the latter.

Do you have any idea where this could be happening? Any thoughts on how I can further troubleshoot it?

KeePass-2.35, KeeAgent-0.9.0.0, Git-for-Windows-2.11.1 (includes OpenSSH_7.3p1), win10_64

**Comment by r2evans** [comment]
On continued testing, I can confirm that I only get the "freeze" behavior when using KeeAgent. When I push after undefining `SSH_AUTH_SOCK` (manually typing in the key password), I have not triggered a freeze.

Does it matter how `ssh` is asking for the key passphrase? When I run `git push ...` on the bash console (using git-for-windows), the first passphrase request is directly on the console, and the second passphrase request is a pop-up window (looking not dissimilar from older "askpass" windows I've seen in linux-past). I don't see this window pop up when using KeeAgent, which is what I expect, but I don't know all of the behind-the-scenes work KeePass/KeeAgent are doing.

@dlech I'm not certain how to give you better information. I infer from the lack of other issues posted that nobody else is impacted by this, suggesting it is my computer alone. I don't have multiple windows workstations from which I can test, so I'm stuck here. Are there hidden logging I can use to gather better information to hunt down whether this is indeed KeeAgent or something else in the chain?

Thanks.

**Comment by dlech** [comment]
Unfortunately, there isn't any debug logging. So, really the only thing to do is attach a debugger when this happens.

It sounds like you are using the confirmation feature of KeeAgent (even though you don't explicitly say it). I think there is some potential for a deadlock with that that has never been addressed, which could be the source of the problem. I'll poke around next time I am in the source code.

**Comment by r2evans** [comment]
- [ ] *"Always require user confirmation when a client program requests to use a key"* is **not selected**
- [x] *"Show a notification whenever a key is used by a client program"* is **selected**
- [x] *"Show key selection dialog when a client program requests a list of keys"* is **selected**

I'm using the cygwin-compatible socket file; I think I found the msysGit socket file not working within git-for-windows.

This gives me another factor to test/control: confirmation of key use. I'll test it for a number of commits and report back.

**Comment by dlech** [comment]
Ah. I think there is some code using low level windows stuff to make the key selection dialog system modal, which could explain why it locks up windows explorer locks up. I will try playing around with that.

**Comment by r2evans** [comment]
(I can only have "so many" not-small commits for testing, thought I'd provide an update.)

I just pushed a large batch of commits with both of the options (*"show a noti..."* and *"show key sel..."*) **not selected** (change from before). It **did not** freeze windows explorer.

**Comment by r2evans** [comment]
Ha, just triggered it again. This time, I re-enabled *"show a notification"* and forwarded the agent connection to a remote server. When the remote side requested a key, I got the notification (correct) and things worked fine on that end, but **windows explorer froze** as before. So, it seems like it's the notification that could be causing it. Perhaps it isn't the key selection dialog (or not "just" that dialog) that's causing things?

**Comment by r2evans** [comment]
Just ran it reversing the selections. With *"show a notification"* **not selected**, and *"show key selection"* **selected**, it did not freeze windows explorer.

**Comment by dlech** [comment]
OK, so it sounds like this is a combination of the showing the notification and showing the key selection dialog that is causing things to hang.

**Comment by r2evans** [comment]
It has not hung with *notifications* disabled, with or without *"show key"*. I apologize for the confusion of rapid-fire permutations. To clear it up:

| notification | key_selection | freeze |
|:------------:|:-------------:|:------:|
|      X       |       X       |   Y    |
|              |       X       |   n    |
|      X       |               |   Y    |
|              |               |   n    |

I *think* this suggests "notifications" alone are the culprit. I'll have some more sizable commits today, I'll advise if I find anything different.

**Comment by r2evans** [comment]
FYI, it's been a week, and all my tests are consistent with the last assertion: I can perfectly correlate freezes with "notification" selected, key-selection dialog has no impact. I'll be happy to alpha-test it it will help, though deselecting "notification" is not an inconvenience.

(Frankly, as I play with the two in various combinations, I can see the need for either "key-select" or "notify", but selecting both is almost entirely redundant in normal use. The key-selection dialog is a good enough indicator that a connection is established and a key is about to be passed.)

**Comment by r2evans** [comment]
May be related: just saw an article describing changes coming in Windows Insider Preview Build 15046:

> We fixed the issue causing Microsoft Edge and / or the taskbar to stop responding requiring you to open Task Manager to restart explorer.exe.

**Comment by dlech** [comment]
Is this still an issue?

**Comment by r2evans** [comment]
I don't think so. I don't know when it cleared up, but I've been using notifications for a while now with no apparent freezes. Sorry for not closing this earlier, thanks for following up.

Just curious, had you made any changes in the low-level windows modals?

**Comment by dlech** [comment]
No, I can't think of any changes that would have affected this.

**Comment by r2evans** [comment]
For confirmation, I've been using *confirmations* vice *notifications* for the last several days (ever since I started using agent-forwarding again and I saw some spurious notifications), and have seen no problems there, either. \*shrug\* Thanks for the awesome tool! I use it everyday and cannot fathom dealing without it.
