### ISSUE TITLE
Keys moved to other directory, KeeAgent keeps looking in the old directory

### ISSUE THREAD

**Issue by pven** [dlech/KeeAgent#185]
I moved my keys to another directory. Unfortunately KeeAgent keeps looking in the old directory. When I look at 'Manage KeeAgent' the moved keys are not there, so I can not remove them.

How can I remove them?

**Comment by dlech** [comment]
What is...

* Operating system:
* KeePass Version:
* KeeAgent Version:
* Agent mode or Client mode:

**Comment by pven** [comment]
Operating System: Windows 8.1
KeePass version: 2.34
KeeAgent version: 0.8.1.0
Agent mode or client mode: I guess agent mode, where can I find this?

**Comment by dlech** [comment]
> where can I find this?

In the titlebar of the KeeAgent manager window.



> I moved my keys to another directory.

Are these saved on disk (external to KeePass) or as attachments in KeePass? If they are on disk, you need to update the corresponding password entries with the new path.

**Comment by pven** [comment]
You triggered me, thanks. I forgot I've added them as a Keepass-entry. Fixed ...

Thanks!
