### ISSUE TITLE
Unexpetected Error when loading a 16384 rsa key

### ISSUE THREAD

**Issue by SkyBlock4000** [dlech/KeeAgent#186]
When i try to load a 16384 rsa key with the plugin in keepass the errormessage in the screenshot is shown.
![screenshot_1](https://cloud.githubusercontent.com/assets/5709618/22919336/9dea87c6-f28f-11e6-818e-68d05c0e7ff6.png)
Tested with a OpenSSHKey and Puttykey.
Password is right.
RSA Key - 16384 - SSH2 RSA
The Key is working with Puttyagent
In the Settingsdialog from KeePass the right id and comment is shown, only loading doesn't work.
4096 RSAKey works fine.
![3](https://cloud.githubusercontent.com/assets/5709618/22919488/77879794-f290-11e6-82e4-49357577a98b.png)
![4](https://cloud.githubusercontent.com/assets/5709618/22919490/79cdfd5e-f290-11e6-9d3b-1b3442599665.png)
Loaded with Pagent directly
![unbenannt](https://cloud.githubusercontent.com/assets/5709618/22919534/ac26a134-f290-11e6-8a14-1e252e793b37.PNG)
Versions:
KeePass 2.35
KeeAgent 0.8.1.0

**Comment by SkyBlock4000** [comment]
Update:
Error only occurs in clientmode. Agentmode is fine.

**Comment by SwadicalRag** [comment]
I'm having the same issue with a 16384 bit ssh key, how did you switch to agentmode @SkyBlock4000 ?

**Comment by SkyBlock4000** [comment]
@SwadicalRag Tools->Options
![grafik](https://cloud.githubusercontent.com/assets/5709618/23329535/015e00ae-fb3b-11e6-9b47-3469262eca89.png)

If the mode is set to auto KeeAgent uses clientmode if a Agent(pagent or in linux some other program) 
is running. But if there is no program it will start in agentmode.
So if you got this error please be sure no other agent is running. Git-clients (for example sourcetree) often start a agent in the background!

**Comment by dlech** [comment]
Fix has been released in v0.9.1. http://lechnology.com/2017/03/keeagent-beta-0-9-1-released/
