### ISSUE TITLE
KeeAgent Icon huge in Mint Tray

### ISSUE THREAD

**Issue by chris42** [dlech/KeeAgent#187]
Hi there,
probably a small issue, but on right click on the keepass icon the icon for keeagent is huge, distorting the menu.
I am using keepass2-plugin-tray-icon on Mint 18.1

Regards
  Chris

**Comment by dlech** [comment]
This would be a bug with the `keepass2-plugin-tray-icon` then. Perhaps a duplicate of <https://github.com/dlech/Keebuntu/issues/32>?

**Comment by chris42** [comment]
Jepp, that is it.
