### ISSUE TITLE
<Error loading key from attachment>  with 0.9.1.0 on Fedora 25

### ISSUE THREAD

**Issue by Erreu** [dlech/KeeAgent#190]
Hi,

Is there a way to enable debugging or logging for KeePass/KeeAgent?

I am getting the error message `<Error loading key from attachment>` when trying to enable the attached test keys. I tried in both client mode and agent mode.
Fedora 25
KeePass 2.34
KeeAgent 0.9.1.0

The steps I followed:
"Add Entry..."
Title: TEST
Password: test1
"Advanced" tab, click "Attach", choose "id_rsa", click "Open"
"KeeAgent" tab
Check "Allow KeeAgent to use this entry"
Check "Attachment", select "id_rsa".

Not sure if it's relevant, but when I try to add the file from the KeeAgent Manager, the error message is "File 'id_rsa' failed with error: see inner exception"

[id_rsa.zip](https://github.com/dlech/KeeAgent/files/849593/id_rsa.zip)

**Comment by dlech** [comment]
This key is working for me on Ubuntu. Perhaps you are missing some Mono dependency? There is no debug logging, unfortunately.

**Comment by Erreu** [comment]
Thank you for the quick reply and your excellent software. I'm sorry, I should have mentioned that KeeAgent 0.8.1 imports the keys without error. The error only occurs when when I try to use 0.9.1.0. I am using Mono version 4.4.2 installed from packages. I *think* I have all the dependencies installed...

**Comment by dlech** [comment]
I forgot to ask if you are using Agent mode or Client mode. Now that I am thinking about it, I only tested in Client mode.

**Comment by Erreu** [comment]
First I tried agent mode because I'd already disabled gnome-keyring-ssh. When that failed I enabled ssh-sgent and tried it in client mode. FWIW, I also tried it in SELinux permissive with semodule -DB just in case, but no SEL blocks were logged.

**Comment by dlech** [comment]
So you get an error in both Agent mode and Client mode?

**Comment by Erreu** [comment]
Yes, Beta_v0.9.1 in client mode and agent mode shows the error "<Error loading key from attachment>". However, v0.8.1 works in both modes.

You're taking this very seriously and I want to help. I spun up a fresh Fedora 25 instance to test with. I installed KeePass and KeeAgent and the test keys that I posted here. If you'd like access, PM me your public key and I'll add it so you can connect with ssh and/or x2go (MATE).

**Comment by dlech** [comment]
Sorry I never got back to this. Please try https://lechnology.com/2018/01/keeagent-beta-0-9-3-released/

**Comment by dlech** [comment]
outdated
