### ISSUE TITLE
Cygwin compatible socket file problem

### ISSUE THREAD

**Issue by aleoliva** [dlech/KeeAgent#191]
Hello,

I use keeAgent together with Cygwin. Following documentation, [link](http://lechnology.com/software/keeagent/usage/options-and-settings/), it works out of the box, e.g.:
```bash
$ echo $SSH_AUTH_SOCK
/var/keeAgent/socket.file

$ ssh-add -l
2048 SHA256:**************** 2015-12-12.key (RSA)
```

However when a second process is already reading that socket, I cannot access to my public keys anymore (no response), e.g.:
```bash
$ ssh -o 'DynamicForward localhost:8081' jumpServer1 &
[1] 2460

$ ssh-add -l
```

**Comment by dlech** [comment]
Which version of KeeAgent are you using? I thought that I fixed that already.

**Comment by aleoliva** [comment]
Ups, sorry _dlech_. My fault. I should have check versions before.

Yes, I had v0.6.3 and upgrading to v0.8.1 the issue is solved.

Thanks.
