### ISSUE TITLE
KeePass 2.35 incompatibility reported during start up

### ISSUE THREAD

**Issue by happy-joe** [dlech/KeeAgent#192]
Hello,

During startup of Keepass 2.35 and compilation of plug-ins on Win7 SP1 64-bit, when KeeAgent (version 0.8.1 or 0.9.1) I'm getting error: Following plugin is incompatible with the current KeePass version: KeeAgent.plgx. Detailed info in attached printscreen.
![2017-03-26_201102](https://cloud.githubusercontent.com/assets/8388669/24333887/85a71a80-1260-11e7-91ad-1b55d4126e69.png)
If you need more details, I'm happy to provide.

Thank you for your help in advance,

Joe

**Comment by dlech** [comment]
KeeAgent requires .NET 4.0. Make sure you have it installed and that KeePass.exe.config is configured to start KeePass using .NET 4.0.

**Comment by happy-joe** [comment]
I have installed .NET 4.6.1. Which obviously doesn't work, but when I try to install 4.0, it rejects it because: Same or higher version of .NET Framework 4 has already been installed on this computer. Thank you.

**Comment by dlech** [comment]
I did not think that you could use/install .NET 4.5+ on XP. Perhaps you should uninstall 4.6.1 and install 4.0.

**Comment by stubbybubby** [comment]
I also get an error message saying the plugin is incompatible.

Here is what I get for "apt show" on my version:
```
Package: keepass2
Version: 2.35+dfsg-2
Priority: optional
Section: utils
Maintainer: Debian CLI Applications Team <pkg-cli-apps-team@lists.alioth.debian.org>
Installed-Size: 3,175 kB
Depends: mono-runtime (>= 3.0~), libmono-corlib4.5-cil (>= 4.6.1.3), libmono-system-drawing4.0-cil (>= 4.6.1.3), libmono-system-security4.0-cil (>= 1.0), libmono-system-windows-forms4.0-cil (>= 1.0), libmono-system-xml4.0-cil (>= 4.6.1.3), libmono-system4.0-cil (>= 4.6.1.3), libx11-6 (>= 2:1.6.0)
Recommends: xsel
Suggests: keepass2-doc, mono-dmcs, xdotool
Homepage: http://keepass.info/
Tag: role::program
Download-Size: 1,338 kB
APT-Manual-Installed: yes
APT-Sources: http://http.us.debian.org/debian stretch/main amd64 Packages
Description: Password manager
 KeePass is a easy-to-use password manager for Windows, Linux, Mac OS X and
 mobile devices. You can store your passwords in highly-encrypted databases,
 which can only be unlocked with one master password and/or a key file.
 A database consists of only one file that can be transferred from one computer
 to another easily.
 KeePass can import data from various file formats. The password list can be
 exported to various formats, including TXT, HTML, XML and CSV files.



```

I am using the beta version 9.1 for KeeAgent as listed on your site.

**Comment by stubbybubby** [comment]
Update: Solved the issue by "sudo apt-get install"ing mono-complete.
