### ISSUE TITLE
Documentation of tempPath location on Linux systems

### ISSUE THREAD

**Issue by linkp** [dlech/KeeAgent#194]
Where does "Save attachment to temporary file when key is loaded" store the temporary key (on Linux)? The placeholder options for URL overrides seem to work for some Windows and even Linux use cases, but I would prefer to point to the temporary file location in the Identity section of my ~/.ssh/config file. If that is possible it would facilitate proper key selection without having to maintain an extra copy of my keys on my filesystem outside of my KeePass database.

**Comment by dlech** [comment]
It looks like we are using [UrlUtil.GetTempPath()](https://github.com/dlech/KeeAgent/blob/master/KeeAgent/KeeAgentExt.cs#L1020) from [KeePass](https://github.com/dlech/KeePass2.x/blob/b2ab2338d35352b9bc758df1aa0ea6fe9c226a49/KeePassLib/Utility/UrlUtil.cs#L609).

On Linux, that calls [GetUserRuntimeDir()](https://github.com/dlech/KeePass2.x/blob/b2ab2338d35352b9bc758df1aa0ea6fe9c226a49/KeePassLib/Native/NativeMethods.cs#L177).

So, it will save things in `$XDG_RUNTIME_DIR/KeePass/` if that environment variable is set or `/home/$USER/.local/share/KeePass/` otherwise.

**Comment by linkp** [comment]
Thanks for sharing that.

My Ubuntu 14.04 environment is using the `$XDG_RUNTIME_DIR` location, `$XDG_RUNTIME_DIR/KeePass/KeeAgent/` to be specific.

Testing revealed that ssh does not expand the `$XDG_RUNTIME_DIR` variable if I use it to define the identity file location in my `~/.ssh/config`, so I substituted the value in the config file and it looks like it would work, if the permissions were not wide open on that folder. Can the permissions on `$XDG_RUNTIME_DIR/KeePass`, or at least `$XDG_RUNTIME_DIR/KeePass/KeeAgent` and the keys contained therein be set to 700/600 instead of 775/664 respectively?

Actually, even just setting the keys to 600 ought to make it work.
Is there a feasible way to make that happen?

`$ ls -ld $XDG_RUNTIME_DIR`
`drwx------ 13 me me 320 Apr 12 14:15 /run/user/1000`
`$ ls -ld $XDG_RUNTIME_DIR/KeePass`
`drwxrwxr-x 3 me me 80 Apr 12 15:01 /run/user/1000/KeePass`
`$ ls -ld $XDG_RUNTIME_DIR/KeePass/KeeAgent`
`drwxrwxr-x 2 me me  80 Apr 12 15:18 /run/user/1000/KeePass/KeeAgent`
`$ ls -l $XDG_RUNTIME_DIR/KeePass/KeeAgent/`
`-rw-rw-r-- 1 me me 3326 Apr 12 15:01 id_rsa`

**Comment by linkp** [comment]
I just noticed that the key files are not getting deleted from that directory when they are unloaded via KeeAgent. I can submit a separate issue on that if you would like.

**Comment by dlech** [comment]
> I just noticed that the key files are not getting deleted from that directory when they are unloaded via KeeAgent. I can submit a separate issue on that if you would like.

I've just pushed some fixes for this and some of the other issues you mentioned. For future reference, please open one issue per problem, otherwise these things tend to get forgotten.

Leaving this open for the original problem, which is need of documentation.

**Comment by dlech** [comment]
docs have been updated

https://keeagent.readthedocs.io/en/stable/usage/options.html#entry-settings
