### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by aneeshusa** [dlech/KeeAgent#195]
First off, thanks for this great software - I just started using it and it's a really nice addition to my workflow!

I have a documentation suggestion for something that really tripped me up when I was first getting started. It seems that when adding new keys to KeeAgent, they need to be added as attachments and then saved via `OK`, before checking the `Allow KeeAgent to use this entry box`. I tried to add key files as attachments and check the box at the same time, which caused `Error loading key from attachment` errors. The [documentation](https://lechnology.com/software/keeagent/usage/quick-start/) does mention to press OK after adding the attachment, but it would have been helpful if it called that step out as required - I saw the new file show up in the attachments list and assumed it had been fully added.

Also, it would be nice if the docs were in-tree, both to support offline usage and to make it possible to send in documentation PRs :)

**Comment by dlech** [comment]
> Also, it would be nice if the docs were in-tree, both to support offline usage and to make it possible to send in documentation PRs :)

This is now possible.

**Comment by dlech** [comment]
https://keeagent.readthedocs.io/en/stable/
