### ISSUE TITLE
rsa -16384 bit key cannot load

### ISSUE THREAD

**Issue by jyf007** [dlech/KeeAgent#197]
OS: Windows 10 1703 15063.296
Keepass Version 2.35
KeeAgent Version 0.8.1
select key from database

![image](https://cloud.githubusercontent.com/assets/17245835/26276050/921a5482-3da1-11e7-8b40-0be0c4c35ae6.png)

![image](https://cloud.githubusercontent.com/assets/17245835/26276014/9ae78a36-3da0-11e7-89ef-9b6412bdfc21.png)

it return this

I have try the maxium length of rsa key -- 16384 bit
the Chinese means "cannot turn the stream's length expand to large than it can"
and "在" means "in"

**Comment by dlech** [comment]
Please try the 0.9.x beta version. I may have fixed this already.

**Comment by jyf007** [comment]
thank a lot

**Comment by jyf007** [comment]
another issue
