### ISSUE TITLE
RFE: Copy Public key also in the Manage KeeAgent Window

### ISSUE THREAD

**Issue by lars18th** [dlech/KeeAgent#199]
Hi,

I suggest to add one simple enhancement:

The KeeAgent has the function "Copy" of "Public key for pasting into authorized_keys". This function is in the Edit Entry, in the section KeeAgent. It's very useful.

However, this function (the same function, no new code needed) can be also useful in the Manage KeeAgent Window. For example, if you click in one loaded key then you directly copy the Public Key to the clipboard.

Why add this in to this Window if it's already in the Edit window? Two reasons:

1) When you have loaded one key, is more simple to go to the Manage KeeAgent Window (only one click to open). It's a good place to see your keys.

2) When you use the "Client Mode" or another Pagent is running (for example, for loading SmartCard keys, as do the Wincrypt Pagent), then you can show "external" keys in the Manage KeeAgent Window. However, in this window you can't "copy" the Public Key of these other keys.

So, as the code is the same, and only a simple call is required... please, can you add this function to the Manage KeeAgent Window?

Thank you!

**Comment by lars18th** [comment]
Hi,

I hope the developers will consider add to this simple UI enhancement. :wink:

Also, I have another similar suggestion: "Include a button for 'EXPORT' the public key to a file". This only generates a plain text file (with default extension .pub) with the content of the public entry. When using different systems that UNIXes and the "authorized_keys" files, will be more simple to export and import this file. And yes, you can create the file with a text editor and paste the content of the clipboard. However, in the code is quite simple to generate this file. No? :grinning:

You agree?

**Comment by dlech** [comment]
> Also, I have another similar suggestion: "Include a button for 'EXPORT' the public key to a file".

For this, I just create this file myself and use the existing file attachment feature of KeePass.

**Comment by lars18th** [comment]
Hi @dlech ,

You'll include this function in a future release?
I'll be very grateful.

Thank you!

**Comment by dlech** [comment]
Please try https://lechnology.com/2018/01/keeagent-beta-0-9-3-released/

I have added a context menu to the Key Manager that will let you copy the authorized_keys string

**Comment by lars18th** [comment]
Hi @dlech ,

Please, re-open this issue! The ZIP you pointed...
https://lechnology.com/2018/01/keeagent-beta-0-9-3-released/
contains the version 0.9.2 (date from 2017-12-17), and not the 0.9.3.
Futhermore the "release" at https://github.com/dlech/KeeAgent/releases doesn't have any "binary".

So, it's impossible to check it!
Please, re-upload the correct ZIP.
Thank you! :smile:

**Comment by dlech** [comment]
Thanks for letting me know. I fixed the zip file. (And I never post anything to the GitHub releases page.)

**Comment by lars18th** [comment]
> Thanks for letting me know. I fixed the zip file.

OK. Check it and working! Thank you! :smile: 

> And I never post anything to the GitHub releases page

And why not put the zip file too in the releases page?

**Comment by dlech** [comment]
Having only one download makes it easy for me to see how many times it is downloaded.
