### ISSUE TITLE
Confirmation dialog appears in background

### ISSUE THREAD

**Issue by olegstepura** [dlech/KeeAgent#203]
Hi!

I've got this configuration on Windows:
![2017-10-11 08_55_51-options](https://user-images.githubusercontent.com/534510/31426081-2b41351e-ae62-11e7-8651-f7ab27f4a663.png)

Almost every time I `ctrl+u` to a server the confirmation dialog appears in background (If I do `ctrl+tab` - it's last one, not even near the Keepass). The thing is that confirmation dialog appears after Keepass started shell with ssh, because it appears when access for some key is made.

Maybe you can somehow make this a top-level dialog (maybe setting it `always on top` property).

Thanks!

**Comment by dlech** [comment]
Which version of KeeAgent are you using?

**Comment by olegstepura** [comment]
It's latest stable, `0.8.1`

**Comment by SugoiDev** [comment]
I have the same issue (semi-frequently) as well. Using mostly KiTTY.

Once I ended up digging through my ssh logs on the server, thinking something was wrong with it (using a recovery console, even).

**Comment by olegstepura** [comment]
I may suppose everyone on windows has this issue. Not everyone pays a lot of attention to it (maybe not so many people configure it ask you every time, but it's about security). But I also was stupidly staring at empty black terminal screen until I understand that there is a confirmation dialog somewhere in background.

**Comment by dlech** [comment]
Please try the latest beta version of KeeAgent.

**Comment by olegstepura** [comment]
Should I use `0.9.1` (seems like march version) or is there any one newer?

**Comment by dlech** [comment]
That is the newest one.

**Comment by olegstepura** [comment]
ok, after a quick check it looks like the issue is gone
