### ISSUE TITLE
Error while loading key from entry with ed25519 key.

### ISSUE THREAD

**Issue by momu** [dlech/KeeAgent#205]
I'm using KeePass 2.37 with KeeAgent 0.9.1.0 on Arch. Agent Mode is set to auto.
When I try to load an ed25519 key with KeeAgent (``Load SSH Key`` in context menu) I get the error:
```
KeeAgent: Error while loading key from entry with 'foo/foo.key'
Could not load file from attachment 'foo'
Possible causes:
- Passphrase was entered incorrectly
- File is corrupt or has been tampered
```
I've created the key with:

     ssh-keygen -t ed25519 -f ~/.ssh/foo -C 'foo@bar'  

Loading the key from within Keepass does not work, but when I do with the password copied from the KeePass entry, it works.
```
╰─$ ssh-add ~/.ssh/foo
Enter passphrase for /home/user/.ssh/foo:
Identity added: /home/user/.ssh/foo (foo@bar)

╰─$ ssh-add -l
256 SHA256:2cFE7DUrVz0QtjKZoHb2T7VOOJbBMTEYzh+OPUALcw8 foo@bar (ED25519)
```
The KeeAgent tab of the entry says: ``<Error loading key from attachment>``

I've attached the sample kdbx file as zip. Password is ``bar``. 
[foo.zip](https://github.com/dlech/KeeAgent/files/1527202/foo.zip)

Can anybody check if the problem is not only on my side?

**Comment by dlech** [comment]
Thanks for the database to make this easy to reproduce. It turns out that your key file uses aes256-cbt encryption, but only aes256-ceb is implemented in KeeAgent.

I've made one change already that will give a better error message in the future.

I'll add adding CBT mode support to the TODO list.

**Comment by dlech** [comment]
https://stackoverflow.com/questions/6374437/can-i-use-aes-in-ctr-mode-in-net

**Comment by momu** [comment]
Thanks for the reply. Do you have any idea how to create a aes256-cbc with ``ssh-keygen``? As far as I can see there are no options for that.

**Comment by dlech** [comment]
For reference:

https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/sshkey.c.diff?r1=1.55&r2=1.56&f=h

**Comment by dlech** [comment]
@momu it looks like you should be able to pass `aes256-cbc` using the `-Z` argument.

**Comment by dlech** [comment]
Please test: https://lechnology.com/2017/12/keeagent-beta-0-9-2-released/

**Comment by momu** [comment]
Thanks a lot for fixing, my ed25519 keys are working. 

Suprisingly rsa keys stopped working, see #208.
