### ISSUE TITLE
Error while loading key with beta 0.9.2 from entry with rsa key

### ISSUE THREAD

**Issue by momu** [dlech/KeeAgent#208]
I'm using KeePass 2.37 with KeeAgent 0.9.2.0 on Arch. Agent Mode is set to auto.
When I try to load an RSA (4096) key with KeeAgent (Load SSH Key in context menu) I get the error:

```
KeeAgent: Error while loading key from entry with 'foo/foo key rsa'
Could not load file from attachment 'foo_rsa'
see inner exception
Possible causes:
- Passphrase was entered incorrectly
- File is corrupt or has been tampered
```
I've created the key with:

     ssh-keygen -t rsa -b 4096 -f ~/.ssh/foo_rsa -C 'foo@bar'

Loading the key from within Keepass does not work, but when I do with the password copied from the KeePass entry, it works.
```
╰─$ ssh-add  .ssh/foo_rsa
Enter passphrase for .ssh/foo_rsa:                                                                                                                                                                                       
Identity added: .ssh/foo_rsa (.ssh/foo_rsa)
```
```
╰─$ ssh-add -l
4096 SHA256:MQhHL5rz97k5nTdEaFYt8S28IPq1ek6D38NBFNEMfL8 .ssh/foo_rsa (RSA)
```
The KeeAgent tab of the entry says: `<Error loading key from attachment>`

I've attached the sample kdbx file as zip. Password is `bar`.
[foo.zip](https://github.com/dlech/KeeAgent/files/1578977/foo.zip)

Can anybody check if the problem is not only on my side?

**Comment by dlech** [comment]
I cannot repeat the problem. Is KeeAgent running in Client Mode or Agent mode?

**Comment by momu** [comment]
Agent Mode is set to Auto, don't know if it is Client or Agent mode then

**Comment by dlech** [comment]
It will tell you in the title bar of the KeeAgent Manager window.

**Comment by momu** [comment]
Ah, thanks. It says client mode.

**Comment by dlech** [comment]
I still can't reproduce the problem. Apparently, I need to update the error message to print the inner exception so we can see what the actual problem is.

**Comment by pschiffe** [comment]
I have the same problem with all my ssh keys and KeeAgent `0.9.2`. With `0.8.1` it works fine. I'm on Fedora, KeeAgent is running in Client Mode.

**Comment by dlech** [comment]
Since I can't reproduce the problem, it would help if you could do some more testing, for example, does v0.9.1 work? Is it only RSA keys? Anything else you can think of might help.

**Comment by pschiffe** [comment]
`v0.9.1` doesn't work - it acts the same as `v0.9.2`. Keepass version is `keepass-2.36-3.fc27.x86_64`. I have only RSA keys, both `2048` and `4096`. I think the issue #190 is the same, or very similar to mine.

**Comment by Kalekulan** [comment]
I have the same issue.

RSA 4096 bytes keys with Putty Keygen. Works fine when you load them manually "from file", but not as attachments.

**Comment by dlech** [comment]
@Kalekulan, are you also on Linux? What versions of everything are you using?

**Comment by Kalekulan** [comment]
KeePass: 2.37
KeeAgent: 0.8.1.0
PuTTY: 0.70
PuTTYgen: 0.68

Thanks!

**Comment by dlech** [comment]
So Windows?

**Comment by Kalekulan** [comment]
Correct!

**Comment by Kalekulan** [comment]
Do you need any help in reproducing this issue?

**Comment by dlech** [comment]
Yes, that would be helpful.

**Comment by Kalekulan** [comment]
I've generated a 4096bit RSA key using puttygen v. 068 Windows.
[test_files.zip](https://github.com/dlech/KeeAgent/files/1648692/test_files.zip)

**Comment by dlech** [comment]
I have finally been able to reproduce the issue on Fedora (27 Workstation). It appears that the official fedora package calls `mono` with the `--verify-all` option. I haven't figured out which .dll is failing this verification yet, but as a workaround, you can run `mono /usr/lib/keepass/KeePass.exe` to start KeePass and things should get better.

**Comment by dlech** [comment]
Please try: https://lechnology.com/2018/01/keeagent-beta-0-9-3-released/

**Comment by momu** [comment]
Thanks a lot. At least for me it works again.

**Comment by dlech** [comment]
Great. I think we can call this fixed.

@Kalekulan, if you are still having problems on Windows with v0.9.3, please open a new issue and post a screenshot of the error message.
