### ISSUE TITLE
Cannot add external key file (UI glitch)

### ISSUE THREAD

**Issue by zeorin** [dlech/KeeAgent#211]
![2018-02-20-141216_1136x1009_scrot](https://user-images.githubusercontent.com/1187078/36423333-3f6c64a2-1648-11e8-8e31-9dea84182922.png)

Ubuntu 17.10
Mono 4.6.2.7
KeePass 2.36
KeeAgent 0.8.1
HiDPI screen (4K: 3840×2160)

Other installed KeePass plugins:
KeeOtp 1.3.9
KeePassRPC 1.7.3.0
GtkStatusIcon 0.1.2.0

Toggling the checkboxes has no effect.
Tabbing through the UI elements doesn't seem to select a "hidden" option, i.e. it seems to not be there at all instead of merely not being visible.

**Comment by dlech** [comment]
Have you tried KeeAgen v0.9.x?

**Comment by zeorin** [comment]
![2018-02-20-210150_1136x1009_scrot](https://user-images.githubusercontent.com/1187078/36443529-b4dc6b18-1681-11e8-8e94-3e0a4af3ee8d.png)

KeeAgent 0.9.3

Looks slightly different, same result.
Also crashes KeePass, both version 2.36 and 2.38.

Reverted KeeAgent back to 0.8.1 for now.

**Comment by zeorin** [comment]
The crashes may have been due to KeePass2 version 2.38. Reverting to 2.36 has eliminated them.

**Comment by dlech** [comment]
Do you get a stack trace from the crash if you run `keepass2` from the command line using v2.38? If so, please post it here.

**Comment by zeorin** [comment]
If I run 2.38 from the command line the crash doesn't happen. I had this on my Debian testing machine also. Apparently it's a bug in Mono. Once Ubuntu updates Mono it ought to go away. In any case, it's not related to KeeAgent, it's actually a Mono bug.

**Comment by dlech** [comment]
So crashing problem is Mono. Is the original issue with the UI still a problem?

**Comment by zeorin** [comment]
Yes, that's still an issue.

**Comment by Sanaki** [comment]
I haven't seen this error at all myself on 2.38 with KeeAgent 0.10.1.0. If there's any information I can provide to attempt to determine why our experiences diverge, please do let me know.

**Comment by zeorin** [comment]
I switched to KeePassXC a while ago. Closing due to age.
