### ISSUE TITLE
Error with huge keys

### ISSUE THREAD

**Issue by g1franc** [dlech/KeeAgent#213]
I'm trying to load a _huge_ (ssh-rsa 16384) putty ssh key  using the _Load Key SSH_ contextual menu but it crash with an error:

![image](https://user-images.githubusercontent.com/1684721/37028381-61bebdc4-2134-11e8-82a6-d44d3d21e7ba.png)

**Comment by dlech** [comment]
Which version of KeeAgent are you using?

**Comment by g1franc** [comment]
Last stable (0.8.1.0)
Will try with beta.

**Comment by g1franc** [comment]
I confirm it is working with beta version 0.9.3.0
