### ISSUE TITLE
Allow access from non elevated process to pageant

### ISSUE THREAD

**Issue by mnaiman** [dlech/KeeAgent#214]
I run Keepass as elevated (admin) to be protected from other processes on machine - similar as in #164.

It possible to alter either access to MemoryMappedFile of MessageProc function in Pageant window to lower processes.

For Messageproc there is ChangeWindowMessageFilterEx https://msdn.microsoft.com/en-us/library/dd388202.aspx to not filter WM_COPYDATA call.

For MemoryMappedFile there is https://stackoverflow.com/questions/34887587/gaining-access-to-a-memorymappedfile-from-low-integrity-process InterProcessSecurity.SetLowIntegrityLevel(file.SafeMemoryMappedFileHandle)

I can test if one or both needs to be set, but this can solve whole problem.

It has to be set to particular Window handle or MemoryMappedFile to not decrease security of whole Keepass.

**Comment by mnaiman** [comment]
Probable place for change are:
https://github.com/dlech/SshAgentLib/blob/57e7e53e668282c0828dbb6ed42af2c3254f32fd/SshAgentLib/PageantAgent.cs#L406 for MemoryMappedFile 
https://github.com/dlech/SshAgentLib/blob/57e7e53e668282c0828dbb6ed42af2c3254f32fd/SshAgentLib/PageantAgent.cs#L329 for MessageProc

**Comment by mnaiman** [comment]
Fixed in https://github.com/dlech/KeeAgent/pull/219 and https://github.com/dlech/SshAgentLib/pull/9

**Comment by dlech** [comment]
Thank you for the pull request. However, I'm not really seeing the logic of doing this. You state that you run KeePass as an elevated process so that other processes can't touch it, yet, this feature allows other less privileged processes access KeePass.

**Comment by mnaiman** [comment]
This feature is implemented in way, that it does NOT allow lower process to access KeePass process.
It allows only to COPYDATA to Pageant hidden window which is created and data are then passed to MemoryMappedFile.
ChangeWindowMessageFilterEx(hwnd, WM_COPYDATA, ChangeWindowMessageFilterExAction.Allow, ref filterStatus);

By default it is off and can be enabled.

Reason why Keepass is running elevated is to disable other processes to read memory (password) without Keepass consent.

But Pageant is exactly about reading keys when requested and asking for user consent.

**Comment by mnaiman** [comment]
Any update?

**Comment by mnaiman** [comment]
Is it possible to merge this PR?

**Comment by mnaiman** [comment]
any update about merge? its increasing security by keeping Keepass privileged as admin and allow non admin processes to request key (confirmation is added level of security)

**Comment by dlech** [comment]
This should be fixed now. Please test https://github.com/dlech/KeeAgent/suites/5172458555/artifacts/156862998 to confirm.

**Comment by mnaiman** [comment]
Perfect thanks, artifact works as expected.
