### ISSUE TITLE
Splitting the agent from KeeAgent for standalone use

### ISSUE THREAD

**Issue by hifi** [dlech/KeeAgent#216]
Pageant doesn't support any of the constraints OpenSSH does for keys and the embedded agent in KeeAgent supports both of them. It could be rather interesting for a lot of people to have a Pageant compatible standalone agent for Windows that works better - even outside KeeAgent.

Our specific use case is that as we don't embed an agent in KeePassXC and Pageant is quite limited on that regard. I understand this sounds a bit odd coming from me as a developer of said "competing" implementation but I'd say it's a win-win situation as it would encourage more people to use your agent on Windows.

**Comment by dlech** [comment]
The SSH Agent portion of KeeAgent is in a separate library. See https://github.com/dlech/sshagentlib. It should be trivial to create a stand-alone application.

**Comment by dlech** [comment]
Closing since this doesn't affect KeeAgent.
