### ISSUE TITLE
Windows OpenSSH client breaks KeeAgent socket

### ISSUE THREAD

**Issue by josmad** [dlech/KeeAgent#217]
- Running the latest version of Keepass (2.38)
 - Tested with versions 0.8.1 & 0.9.2 of KeeAgent
 - No other plugins
 - Cygwin socket

When the Windows OpenSSH client requests keys I get the same 
`debug1: pubkey_prepare: ssh_fetch_identitylist: invalid format` from #207 

Subsequent attempts to fetch keys by ANY ssh client yields
`debug1: pubkey_prepare: ssh_get_authentication_socket: Bad file descriptor`

Restarting Keepass fixes it until the next run of the Windows OpenSSH client.

**Comment by dlech** [comment]
So you are using both the Cygwin socket and the Windows OpenSSH socket?

**Comment by josmad** [comment]
As in the Windows OpenSSH ssh agent? Or the compatible socket in 0.9.2?

Not using the first.
I'm not sure if I am using the second one, if I have it enabled when I close the options window, it will complain that the Windows OpenSSH ssh agent is already running (service is installed, not sure if it can be removed, but not running).

**Comment by dwatley** [comment]
I get this same issue. If `SSH_AUTH_SOCK` is set as an environmental variable to the cygwin sock file, and I use the Windows OpenSSH Client I get the same break as described here. Cygwin/Git SSH client works at first.

Steps:
1. Start KeeAgent in Agent Mode, set sock file.
1. Use Cygwin SSH client (success)
1. Use Win32 OpenSSH client (failure)
1. Use Cygwin SSH client (failure)
1. Restart KeePass, rinse and repeat.

The fix/workaround is: the SSH_AUTH_SOCK variable has to be *unset before* running the Win32 OpenSSH client, else it corrupts this sock file. This can present some challenges if you're using git and need this variable set.

**Comment by dlech** [comment]
This sounds like a 3rd party issue with a known workaround.

**Comment by i3v** [comment]
> the SSH_AUTH_SOCK variable has to be unset before running the Win32 OpenSSH client

Personally, I rather hardcode `SSH_AUTH_SOCK` in my cygwin scripts.

Without this workaround, the issue is still present in KeeAgent 0.13.8.0 (KeePass 2.58, Windows 10 22H2).
