### ISSUE TITLE
Support Windows/WSL Interop with AF_UNIX

### ISSUE THREAD

**Issue by drujd** [dlech/KeeAgent#220]
https://blogs.msdn.microsoft.com/commandline/2017/12/19/af_unix-comes-to-windows/
https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/

Hello, it would be nice to support (besides Cygwin and msysGit sockets) native AF_UNIX sockets that come with Windows 1803. That way, ssh/KeeAgent interop in WSL should work just by setting SSH_AUTH_SOCK.

That way, in WSL, we wouldn't have to use (possibly unsecure) workarounds such as https://gist.github.com/strarsis/e533f4bca5ae158481bbe53185848d49 or https://github.com/vuori/weasel-pageant .

**Comment by silviuvulcan** [comment]
Right now I'm using [vuori/weasel-pageant](https://github.com/vuori/weasel-pageant) which is abandoned (it uses WSL-Win32 interop used before 1803) and looking to switch to [benpye/wsl-ssh-pageant](https://github.com/benpye/wsl-ssh-pageant) which does offer AF_UNIX but it still means I have to run one more agent just for WSL.

It'd sure be nice to be able to switch to a native solution.

**Comment by BobVul** [comment]
I ended up creating a set of wrapper scripts (https://github.com/BobVul/ssh-pageant-scripts) for benpye/wsl-ssh-pageant. They launch the bridging agent on demand and tied to the lifecycle of the launched application. This at least lets me avoid starting another agent separately/keeping it running forever in the background.

**Comment by mehrdadn** [comment]
I've implemented this for myself currently. Is this project still being maintained as of 2021? And if so, what is the process/policy on contributing code?

**Comment by dlech** [comment]
Still maintained - just very low priority for me right now. Changes with automated tests are more likely to be accepted.

**Comment by mehrdadn** [comment]
Ah I see, I don't have tests or such unfortunately. Was just wondering if I could leave some code here semi-anonymously and have someone handle the rest. I guess if anyone becomes interested in that feel free to ping me. Thanks!

**Comment by dlech** [comment]
Feel free to make a PR even if it is incomplete.

**Comment by mehrdadn** [comment]
Done!

**Comment by mehrdadn** [comment]
I'm guessing you can close this issue now that those are merged. 🙂

**Comment by dlech** [comment]
This was merged in #321.
