### ISSUE TITLE
KeeAgent 0.8.1.0 reporting incorrect passphrase for ed25519 key generated with OpenSSH 7.6p1

### ISSUE THREAD

**Issue by godeater** [dlech/KeeAgent#223]
I'm running KeePass version 2.38 on Windows 7 with version 0.8.1.0 of the KeeAgent plugin.

I've just attempted to add a new key to KeePass for KeeAgent to use, generated with the ssh-keygen.exe that is included in the Msys2 OpenSSH 7.6p1 package. For the purposes of this issue report, I've used 'demo' as the passphrase given to ssh-keygen:

```
$ ssh-keygen -t ed25519
Generating public/private ed25519 key pair.
Enter file in which to save the key (/home/childba/.ssh/id_ed25519):
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/childba/.ssh/id_ed25519.
Your public key has been saved in /home/childba/.ssh/id_ed25519.pub.
The key fingerprint is:
SHA256:xlEC4rkHT7bV1mE2z3KOaa2Cl+iy4EPRYkNeqgksWXw childba@LONMW84148
The key's randomart image is:
+--[ED25519 256]--+
| .  . ... . =    |
|  o.Eo.  + + =   |
|.o +++o o o o +  |
|+.  B*.+ o   B   |
|.. +.++ S   + o  |
|  o .. . o o .   |
|   ..   o + .    |
|   ..... . .     |
|    ...o.        |
+----[SHA256]-----+
```

Corresponding entry in KeePass:
![image](https://user-images.githubusercontent.com/1461/38552622-9873a62c-3cb4-11e8-8783-9b2ff4958637.png)

![image](https://user-images.githubusercontent.com/1461/38552639-a669d74c-3cb4-11e8-8bcd-a2ad15cf320f.png)

![image](https://user-images.githubusercontent.com/1461/38552648-b0e6204a-3cb4-11e8-8fcd-93533f803a63.png)

In the last screenshot, you can see that KeeAgent is reporting a problem loading the key, and if I try to Load the SSH Key from the main UI using Ctrl+L, I get this error:

![image](https://user-images.githubusercontent.com/1461/38552692-dac68314-3cb4-11e8-8980-423d59bf0227.png)

This also appears to be a problem with ed25519 keys generated using the OpenSSH shipped with Git for windows, and with Cygwin. Puttygen ed25519 keys however appear to load ok.

**Comment by dlech** [comment]
Does it work with KeeAgent v0.9.x?

**Comment by godeater** [comment]
I'm such a doofus, I didn't even know there was a KeeAgent 0.9. I will download and check ASAP.

**Comment by godeater** [comment]
I've checked, and nope - doesn't work with 0.9.3 either. 

Slightly different error this time :

![image](https://user-images.githubusercontent.com/1461/38569034-1be47036-3ce2-11e8-947b-fae55cc7bc4d.png)

**Comment by dlech** [comment]
Can you zip the private key and attach it here so that I can try to reproduce the problem?

**Comment by godeater** [comment]
Could probably just have pasted the actual content, ed25519 keys are pretty tiny :)

[id_ed25519.zip](https://github.com/dlech/KeeAgent/files/1895447/id_ed25519.zip)

**Comment by dlech** [comment]
What is the passphrase? I tried `demo`, but that doesn't seem to work.

**Comment by godeater** [comment]
Are you saying it doesn't work with that outside of keepass? That was definitely the passphrase I used - and for me it worked when not using Keeagent as the ssh-agent.

**Comment by markschuh** [comment]
I can't decrypt this private key with password "demo" either. Tested with both Msys2 "OpenSSH_7.7p1, OpenSSL 1.0.2o  27 Mar 2018" as well as "OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4"

ssh-keygen -y -f id_ed25519
Enter passphrase:
Load key "id_ed25519": incorrect passphrase supplied to decrypt private key

**Comment by dlech** [comment]
> Are you saying it doesn't work with that outside of keepass?

Yes. I tried using it with OpenSSH `ssh-add` on Linux.
