### ISSUE TITLE
Not compatible with KeePass 2.39

### ISSUE THREAD

**Issue by dlech** [dlech/KeeAgent#224]
From lechnology.com contact form:

> Thanks for creating this useful plugin.  I thought I'd let you know that you're plugin is no longer working with the Keepass development snapshots that are leading up to version 2.39.  You'll have to ask Dominik for the specifics, but it relates to his following statement:  "In KeePass 2.39, the secure edit control implementation will be improved, and the plugin needs to be adapted for this."

Related message: https://sourceforge.net/p/keepass/discussion/329220/thread/4236e391/#a6fa

(In case you are wondering, KeePass 2.39 has not been officially released yet).

**Comment by mendhak** [comment]
Thank you dlech for reacting this so quickly.  Your work on this plugin is always appreciated.
