### ISSUE TITLE
Problem with Windows OpenSSH agent lifetime

### ISSUE THREAD

**Issue by dlech** [dlech/KeeAgent#226]
from @markschuh https://github.com/dlech/KeeAgent/issues/207#issuecomment-381389630

> There remains only one nuisance for me: Deactivation of the flag does not stop KeeAgent to provide the "openssh-ssh-agent" pipe. An error message "Windows OpensSSH agent is already running." pops up during each close of KeeAgent Global Options dialogue after first activation. But it is KeeAgent itself, which does not stop using the pipe, when instructed to do. I assume, this may be caused by "listeningServer = null;" in line 72 of SshAgentLib/WindowsOpenSshPipe.cs, while stop also references to this variable.

**Comment by ralish** [comment]
Merging the above referenced PR will fix this issue (the issue is in SshAgentLib versus the KeeAgent extension itself).

**Comment by dlech** [comment]
Fixed in https://github.com/dlech/SshAgentLib/commit/55ffc83ec060e6c24b58dd2075a768838a2010c8
