### ISSUE TITLE
Either KeepassRPC or KeeAgent work

### ISSUE THREAD

**Issue by Nama** [dlech/KeeAgent#230]
Hi,
since Windows 10, after I start Keepass for the first time after Windows' boot and unlock of the database, Kee works, but KeeAgent don't.
Putty and Filezilla just don't reconigze the Agent.
I close Keepass, start it again and unlock the database. Putty and Filezilla can connect now, but Firefox and Thunderbird do say "Keepass is not running" and aren't autofilling login forms anymore...

Keepass: 2.38
KeepassRPC: 1.8
Kee (Firefox): 2.3.19.1
KeeAgent: 0.10.1.0

Thanks

**Comment by dlech** [comment]
https://github.com/kee-org/keepassrpc/issues/33

**Comment by Nama** [comment]
I am starting Keepass from a own script via the TaskScheduler and because of another part of it, I let it execute with "higher privileges" - as Administrator. That made KeeAgent not recognizable for all SSH clients.

KeepassRPC/Kee works now mostly after restarting Keepass. I don't know why.
