### ISSUE TITLE
v0.10.1 freezes Keepass 2.38

### ISSUE THREAD

**Issue by Karreg** [dlech/KeeAgent#232]
Hello,

I have updated the plugin to 0.10.1 (from version 0.8.something) this morning with Keepass 2.38, and opening a database is freezing the app.
When removing the plugin, it works again.
Maybe related to #224

**Comment by Karreg** [comment]
When removing the plgx, the version switches back to 0.8.1.
It looks like this is the plgx compilation step that is failing, without error.

**Comment by Karreg** [comment]
My previous statement was wrong. Compiling is fine, opening the database is not.
I have the issue also with version 0.10.0, so it's not related to compatibility with version 2.39 of Keepass...

**Comment by Karreg** [comment]
Nevermind, the issue was just a change in plgx file name, so I had both version at the same time... It's fixed by removing the old file.

**Comment by dlech** [comment]
What is the difference in the names?

**Comment by Karreg** [comment]
I installed the plugin through chocolatey at first, and the plgx file is named keepass-plugin-keeagent.plgx
Also, it is not updated to the latest version.
So I had keepass-plugin-keeagent.plgx and KeeAgent.plgx.
And Keepass does not handle this use case at all...

**Comment by pauby** [comment]
I'm the maintainer of the Chocolatey package mentioned here. I was sent a message by a user of the package but their email address is undeliverable so I can't get back to them.

I was asked if I could handle the issue with the package name changing. I am not keen on arbitrarily removing files from a users system. I am happy to flag up that the other file is there and let the user decide however. 

If you want to let me know your thoughts you can find the issue at https://github.com/pauby/ChocoPackages/issues/15

**Comment by Karreg** [comment]
Thanks, we can discuss this there :)

**Comment by pauby** [comment]
New chocolatey package version pushed and published. It will remove the old plugin version if it finds it.
