### ISSUE TITLE
"require user notification" does not take effect immediately

### ISSUE THREAD

**Issue by r2evans** [dlech/KeeAgent#233]
Steps that reproduce it (for me). Starting from "require user notification" DEselected.

1. Select "require user notification", *do not lock KeePass*;
2. Initiate something that requires an SSH key ("use ssh"), no confirmation required;
3. Lock and unlock KeePass;
4. Use ssh, confirmation is now required;
5. Deselect "require user notification", *do not lock KeePass*;
6. Use ssh, confirmation still required;
7. Lock and unlock KeePass;
8. Use ssh, confirmation not required.

If this is reproducible for others, then I suggest either (a) change it so the effect is immediate, or (b) document that a lock/unlock is required to effect the change.

**Comment by dlech** [comment]
Where are you setting "require user notification"? The global options or on a per-entry basis?

**Comment by r2evans** [comment]
Honestly, I didn't know that there was a per-entry basis for "require user notification". Is that what "Use confirm constraint" means on the single-entry KeeAgent tab?

(I was referring to the global config here.)

**Comment by dlech** [comment]
> Is that what "Use confirm constraint" means on the single-entry KeeAgent tab?

yes

**Comment by dlech** [comment]
FWIW, the internal workings are a bit different, but it basically has the same effect.

**Comment by dlech** [comment]
docs have been updated

https://keeagent.readthedocs.io/en/stable/usage/options.html#global-options
