### ISSUE TITLE
agent failure after upgrading ubuntu

### ISSUE THREAD

**Issue by badpenguin** [dlech/KeeAgent#234]
After upgrading Ubuntu from 17.10 to 18.04 i'm getting this error and i'm unable to use some of my keys stored as attachment.

The error is: 
Agent Failure
Possible causes:
key is already loaded in agent
agent is locked
![https://snag.gy/jMpWbN.jpg](https://snag.gy/jMpWbN.jpg)

However 2 keys are loaded the remaining 4 are not.
Did something change in the supported file formats during the upgrade?

I've already tried to upgrading keeagent.

My current versions are:
-  keepass2  2.38+dfsg-1              
- keepass2-plugin-keeagent 0.10.1

**Comment by dlech** [comment]
I'm assuming that you are running in Client mode. Starting with [OpenSSH 7.6](https://www.openssh.com/txt/release-7.6), the `ssh-agent` program will:

> Refuse RSA keys <1024 bits in length and improve reporting for keys
   that do not meet this requirement.

This affects Ubuntu 18.04 as well as macOS 10.13.

**Comment by badpenguin** [comment]
@dlech thanks! Let me test this :)

**Comment by badpenguin** [comment]
In ubuntu temporary stop openssl upgrade and fix your old insecure keys.

I applied the following apt's preference settings:
```
Package: openssl*
Pin: release v=17.10
Pin-Priority: 1001

Package: openssh*
Pin: release v=17.10
Pin-Priority: 1001
```

**Comment by dlech** [comment]
docs have been updated

**Comment by dlech** [comment]
https://keeagent.readthedocs.io/en/stable/troubleshooting.html#common-issues
