### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by mapagm** [dlech/KeeAgent#238]
Hi,

My problem is that autologin works in Putty only with Pageant but doesn't seem to work with KeeAgent... 
I'm using KeePass 2.39.1, KeeAgent 0.10.1.0. and Putty 0.70. My OS is Windows 7 x64.
I've created keys ssh-rsa 4096, copied public key to .ssh/authorized_keys. Then in KeePass i've followed this tutorial: https://keeagent.readthedocs.io/en/stable/usage/quick-start.html

And now: when I use Pageant, add key with passphrase and open putty session then auto login works like a charm. When I close Pageant, open KeePass, unlock database and try to open putty session i get an error: "Disconnect: No supported authentication methods available (server sent: pubkey)."

Please help.

**Comment by dlech** [comment]
Can you confirm that KeeAgent is running in Agent mode? Also, does PuTTY work if you manually connect rather than using autologin?

**Comment by mapagm** [comment]
I didn't touch any KeeAgent options. I have Agent Mode set to Auto. 
It's strange because on Windows 10 laptop it works! I reinstalled Windows 7 and still nothing - i get Fatal Error "Disconnect: No supported authentication methods available (server sent: pubkey)."....

**Comment by mapagm** [comment]
Ok, it works now! I had to INSTALL KeePass because previously I used portable version.
