### ISSUE TITLE
ppa:dlech/keepass2-plugins not upd-to date, leading to unloading of plugins

### ISSUE THREAD

**Issue by chris42** [dlech/KeeAgent#239]
Hi there,
I was using Keeagent 0.9.3 and KeeRPC 1.7.0 out of the ppa for Ubuntu. Yesterday Keepass2 was updated to 2.39.1
When restarting it was stated, that the plugin versions are not compatible with Keepass2 and were unloaded.
Manually placing the current versions of the plugins does work. Hence the ppa would need anupdate.

Regards
  Chris

**Comment by dlech** [comment]
what operating system/version are you using?

**Comment by chris42** [comment]
Linux Mint 18.3, hence Ubuntu 16.04, Xenial

**Comment by dlech** [comment]
According to launchpad, xenial has been updated to KeeAgent 0.10.1

https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins?field.series_filter=xenial

**Comment by dlech** [comment]
Perhaps you only have the beta ppa? You need both beta and non-beta ppas if you always want the most recent version of packages.

**Comment by chris42** [comment]
That was it, only had the beta ppa. Thanks!
