### ISSUE TITLE
Integration with JetBrains IDEs

### ISSUE THREAD

**Issue by scj643** [dlech/KeeAgent#242]
I am trying to figure out how I can use KeeAgent with the JetBrains IDEs like PyCharm.

**Comment by scj643** [comment]
The do mention KeeAgent in https://blog.jetbrains.com/pycharm/2017/08/ssh-agent-simplify-ssh-keys/ but no instructions on how to use it

**Comment by mendhak** [comment]
Hello again, I assume this is on Windows?

Specify the path to your git executable in the settings

https://www.jetbrains.com/help/idea/settings-version-control-git.html

Although that's for IDEA the same settings are usually present across most Jetbrains IDEs.  Note that it may already be set.

Also, to cater to the terminal, have a look at [this comment](https://youtrack.jetbrains.com/issue/IDEA-152363#comment=27-1434109)

**Comment by scj643** [comment]
Is there anything I have to do for SSH Executable

**Comment by scj643** [comment]
Running the IDE from git bash seems to work

**Comment by scj643** [comment]
So installing Git Bash with all on the path works and setting the ssh to use native instead of built in.

**Comment by ezekielnewren** [comment]
Under Tools -> Options -> KeeAgent. Put `%userprofile%\keeagent.sock` for the path to the Cygwin compatible, also git bash compatible, socket file. And then run the powershell command `[Environment]::SetEnvironmentVariable("SSH_AUTH_SOCK", "$HOME\keeagent.sock", "User")` close KeePass and reopen it then close all of your cygwin, git bash, and jetbrains IDE windows and then start them back up.

![keeagent_set_SSH_AUTH_SOCK](https://user-images.githubusercontent.com/18313324/147777850-626900f6-0d3e-4c61-af32-7d5a47e74586.png)
![powershell_set_SSH_AUTH_SOCK](https://user-images.githubusercontent.com/18313324/147777890-3173068b-1749-46cd-84b2-454701560a39.png)
