### ISSUE TITLE
down: https://lechnology.com/software/keeagent

### ISSUE THREAD

**Issue by heikoh81** [dlech/KeeAgent#247]
Can't reach the URL in order to download KeeAgent :-(
Also posted the issue here: https://github.com/mendhak/keepass-and-keeagent-setup/issues/3

**Comment by dlech** [comment]
It is working for me.

**Comment by mendhak** [comment]
I had trouble reaching it this morning, but it's working just fine now

**Comment by heikoh81** [comment]
It's working again for me, as well.
Shouldn't the file itself also be hosted here on GitHub for reliability?
