### ISSUE TITLE
Loging second instance by console problem.

### ISSUE THREAD

**Issue by MorGotHMGH** [dlech/KeeAgent#249]
I have a problem when login on third host using Keeagent. When I login by putty to first server, keeagent getting private key from keepass and login me, then from console "ssh to_some_second_ip" and here everything is ok and loging with private key, when I try to "ssh to_some_third_ip" putty can't import private key and I must give the password. Is this Keeagent issue or putty. Is there any walkaround to login third time by Keeagent and using private key?

**Comment by markschuh** [comment]
Does not sound like a KeeAgent issue, but just a not used "ForwardAgent" from first_server to second_server. As long as you are were aware of the pitfalls of forwarding agent connections (1) and you trust your second_server enough you might activate it via "-A" or on each ssh request with "to_some_second_ip" by configuring your ~/.ssh/config on first_server. Also second_server's sshd must allow you to use Agent Forwarding (what is the default)

Besides that I think, switching identities (logins) within a ssh agent forwarding cascade (except the last hop) may introduce more challenges - even when everything above is in place.

(1) http://rabexc.org/posts/pitfalls-of-ssh-agents

**Comment by MorGotHMGH** [comment]
Yes you right, just need to set in Putty -> "Allow agent forwarding" and use "ssh -A host_ip" to login. Thank you for response.
