### ISSUE TITLE
Locking up when syncing to scp with KeeAgent loaded

### ISSUE THREAD

**Issue by davidaue** [dlech/KeeAgent#254]
1) Open local keepass database file.
2) File > Synchronize with URL... > scp://something.com:2222/backup/keepass.kdbx
3) Supply user name and password and hit Ok
4) UI locks up forever, (Not Responding) in title bar.

I am using IOProtocolExt for scp syncing. If I remove the KeeAgent plugin the sync works.

**Comment by dlech** [comment]
Yeah, this won't work if you set KeeAgent to require confirmation on this entry. KeePass has a single UI thread and IOProtocolExt blocks this thread waiting for KeeAgent, but KeeAgent can't show the confirmation dialog because the UI thread is blocked.

**Comment by davidaue** [comment]
Turning off the key selection dialog fixes the problem. User confirmation can be left on. What was confusing is that IOProtocolExt is requesting keys even when I enter a password. Thank you so much for your help.
