### ISSUE TITLE
[enhancement] optionally send keepass to background from Key selection dialogue

### ISSUE THREAD

**Issue by dugite-code** [dlech/KeeAgent#258]
I have the interface option `Drop to background after copying data to the clipboard` disabled. With KeeAgent using the Key selection dialogue, after selecting a key, keepass is sent to the background.  

I would love to have a way to disable this, perhaps an option in the KeeAgent options or just by following the existing interface option.

KeeAgent: 0.10.1.0
Keepass: 2.41
Operating system: Windows 10

**Comment by jfut** [comment]
Thanks for the very useful software.

I have a similar problem.

If there are multiple key selection dialogs, when I close the first dialog, KeePass window is sent to the background.
So to select the second dialog, I have to click on the KeePass window from the taskbar to show it again and then select a key.

1. Run `ssh host` on terminal 1, then `Select a Key` dialog 1 is opened.
2. Run `ssh host` on terminal 2, then `Select a Key` dialog 2 is opened.
3. Select the key from dialog 1, then both KeePass window and dialog 2 is sent to the background.

I'd be happy if all the `Select a Key` dialogs were always kept on top.

- KeeAgent v0.12.0
  - [x] Show key selection dialog when a client program requests a list of keys
- KeePass 2.45
  - [x] Always on Top
  - [ ] Drop to background after copying data to the clipboard
- Windows 10 Pro Version 2004

**Comment by dlech** [comment]
This is fixed by https://github.com/dlech/KeeAgent/pull/394.

**Comment by jfut** [comment]
Thank you! I confirmed that it works as expected in the latest build of GitHub actions:
https://github.com/dlech/KeeAgent/actions/runs/7604354479
