### ISSUE TITLE
Repeated Secure Desktop Notification (Windows)

### ISSUE THREAD

**Issue by leonard84** [dlech/KeeAgent#259]
When Keepass is locked and a password is requested by git via KeeAgent, it triggers a dialog to unlock Keepass (when the screen is locked too). The problem is that the notification dialog is opened repeatedly for each request, instead of just having one open you can get multiple. Furthermore, each dismiss of the dialog triggers another SecureDesktop login, even if it is already unlocked by a previous dialog.

According to https://sourceforge.net/p/keepass/bugs/1842/ it should be an issue of KeeAgent

![KeepassStacking](https://user-images.githubusercontent.com/1151511/56603488-1f240c00-6600-11e9-974a-87beb266bf58.png)

**Comment by dlech** [comment]
Duplicate of #227?

**Comment by leonard84** [comment]
It seems to be fixed in keepass 2.42
