### ISSUE TITLE
OpenSSH simple certyficates

### ISSUE THREAD

**Issue by madejusz** [dlech/KeeAgent#262]
Correct me if I'm wrong, but look like KeeAgent not supporting OpenSSH certificates. Do you plan to add such option?

**Comment by dlech** [comment]
No immediate plans.

**Comment by msabatier** [comment]
Hi,

First I would like to thank David @dlech for this great plugin.

I have been successfully using KeeAgent with openssh certificates for more than a year now with 2 different setups
1- use windows 10 openssh client and activate option "Enable agent for Windows OpenSSH". In this scenario connecting directly to the target server with an openssh certificate works
2- use putty to ssh into a bastion host using normal key then use ssh agent forwarding to connect to the target server with an openssh certificate. 
In both cases the private key stays in KeeAgent 

@madejusz could you explain your use case ?
My feeling is that the issue has more to do with your ssh client than KeeAgent.

**Comment by dlech** [comment]
support for certificates has been added in https://github.com/dlech/KeeAgent/releases/tag/v0.13.1
