### ISSUE TITLE
breaking changes expected in KeePass 2.43

### ISSUE THREAD

**Issue by dlech** [dlech/KeeAgent#265]
from the website contact form:

> Heads up...
> 
> Dominik's latest development snapshot has broken your plugin.  Here's the thread:  https://sourceforge.net/p/keepass/discussion/329220/thread/4d5c244796/?limit=250#ddaa

**Comment by FrozenDragoon** [comment]
It looks like these changes did make it into 2.43, and that the plugin did broken. 
![2019-09-10 08_57_50-001319](https://user-images.githubusercontent.com/5301673/64620303-3bef8f00-d3a9-11e9-98c5-90f681964d20.png)

**Comment by NickPyz** [comment]
CONFIRMED.

Upgraded to new KeePass release (2.43 - Windows) and KeeAgent plugin fails to load. Same error message as FrozenDragoon.

**Comment by gjf** [comment]
I can confirm this. The error exists both for stable and beta.

**Comment by grazzolini** [comment]
I'm the maintainer of both keepass and keeagent for Arch Linux and I can confirm that keepass 2.43 breaks the keeagent plugin.

**Comment by afischer211** [comment]
Are there any plans for making keeagent compatible to the new keepass-version?

**Comment by strarsis** [comment]
Just encountered the same issue after upgrading to 2.4.3,
KeeAgent is an awesome and very helpful plugin, please keep maintaining it!

**Comment by dlech** [comment]
https://sourceforge.net/p/keepass/discussion/329221/thread/fca8312093/?limit=250#62a9

**Comment by dlech** [comment]
Please try https://github.com/dlech/KeeAgent/releases/tag/v0.11.1

**Comment by dmstewart42** [comment]
v0.11.1 is working for me.
Thank you for fixing this so quickly!

**Comment by koddistortion** [comment]
Nice work and thanks for the lightning fast hotfix!

**Comment by silviuvulcan** [comment]
v0.11.1 Working for me too. Should have checked releases before the issues page. Thanks !

**Comment by jyf007** [comment]
but v0.11.1 don't works in mono. my mono is here 
Mono JIT compiler version 6.0.0.313

**Comment by afischer211** [comment]
Thanks for the very quick hotfix. Works smoothly under Windows10 with Keepass 2.43

**Comment by grazzolini** [comment]
@dlech, sure, but I don't package the beta version on Arch, only the stable one. I can probably backport the fixes.

**Comment by dlech** [comment]
FWIW, the other changes in the beta version have been in tested for at least 6 months, so it might be worth making an exception in this case. I should be releasing a new stable version fairly soon anyway because of this issue.

**Comment by RoSk0** [comment]
Any plans to push 0.11.1 to PPA?

**Comment by dlech** [comment]
0.11.2 is available in the beta ppa now. https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins-beta

**Comment by Zumochi** [comment]
Are there any plans to make a stable release that include this fix?

**Comment by dlech** [comment]
Yes, when I can find some time.

**Comment by chris42** [comment]
Any plan on moving this to stable?
