### ISSUE TITLE
KeeAgent fails to load under KeePass v2.43

### ISSUE THREAD

**Issue by knh1** [dlech/KeeAgent#268]
Get the following error when KeePass tries to compile/load plugin on startup:

```
KeeAgent failed to load:

Insertion index was out of range. Must be non-negative and less than or equal to size.

Parameter name: index
```

Error occurs with both stable v0.10.1 and beta v0.11.0.

**Comment by dlech** [comment]
Duplicate of #265

**Comment by knh1** [comment]
Sorry, should have looked closer.  Thanks for fixing so quickly!
