### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by nyn3x** [dlech/KeeAgent#269]
I just updated to KeePass 2.43 and now KeeAgent fails to load:

![image](https://user-images.githubusercontent.com/581049/64673546-bdf5bb80-d46e-11e9-8376-d3fa0e771f92.png)

I've tried 0.10.1 as well as 0.11

**Comment by Sieboldianus** [comment]
This bug is also confirmed (and explained) [here](https://sourceforge.net/p/keepass/discussion/329221/thread/fca8312093/?limit=25)

**Comment by silviuvulcan** [comment]
Here is an english version of the error:

```
KeeAgent failed to load:
Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
```

For now I downgraded back - I depend completely on keeagent. But @dlech in case you want me to test a beta version I am at your disposal.

**Comment by igrep** [comment]
Duplicate with https://github.com/dlech/KeeAgent/issues/265.

**Comment by dlech** [comment]
https://lechnology.com/2019/09/keeagent-beta-v0-11-1-release/
