### ISSUE TITLE
KeeAgent failed to load with new KeePass 2.43

### ISSUE THREAD

**Issue by WAdama** [dlech/KeeAgent#270]
Hi,
during start of new KeePass 2.43 I've got the following error message:
KeeAgent failed to load
German:

> Der Einfügeindex liegt außerhalb des gültigen Bereichs. Der Index darf keine negative Zahl sein und muss kleiner oder gleich der Größe sein.
> Parametername: index

Google translator makes this of it:

> The insert index is out of range. The index can not be a negative number and must be less than or equal to the size.
> Parameter name: index

**Comment by igrep** [comment]
Duplicate with https://github.com/dlech/KeeAgent/issues/265

**Comment by dlech** [comment]
https://lechnology.com/2019/09/keeagent-beta-v0-11-1-release/
