### ISSUE TITLE
but v0.11.1 don't works on mono and keepass 2.43

### ISSUE THREAD

**Issue by dlech** [dlech/KeeAgent#271]
but v0.11.1 don't works on mono and keepass 2.43
it says "Cannot load plugin ,needs update .NET Framework "in Chinese.
my mono is Mono JIT compiler version 6.0.0.313 
and i using gentoo https://packages.gentoo.org/packages/dev-lang/mono

_Originally posted by @jyf007 in https://github.com/dlech/KeeAgent/issues/265#issuecomment-530290214_

**Comment by dlech** [comment]
Hmm... I bumped the minimum .NET version to 4.5, however this has been the minimum version provided by mono for quite some time. I will try to test soon.

**Comment by dlech** [comment]
https://github.com/dlech/KeeAgent/releases/tag/v0.11.2

**Comment by taurus-forever** [comment]
The fix has been confirmed:

Linux Mint 19.2
keepass2: 2.43+dfsg-1~ubuntu18.04~ppa1
keeagent: 0.11.2
mono-4.0-gac: 4.6.2.7+dfsg-1ubuntu1

Thank you. Sent $10 for the fast fix here! ;-)
Please release the package in stable/beta channels.

**Comment by ckolumbus** [comment]
Confirmed to work on Manjaro 18.1.4 ! THANKS!
Only the 0.11.2 is listed as '0.11.1.0' in the Plugins overview list within KeePass itself.
