### ISSUE TITLE
Documentation on beta versus stable

### ISSUE THREAD

**Issue by h4knet** [dlech/KeeAgent#274]
Hello,

I'm used to get the stable version of KeeAgent however it's no more compatible with the latest release of KeePass.

I search through the documentation and the GitHub project but I didn't find any details about the changelog or differences between the stable version and the beta.

Would you explain these differences please to help users understand the differences and updates provided by the beta version of KeeAgent ? 

Thank you anyway for your useful tool ! 👍 

Regards,

**Comment by dlech** [comment]
Changelog: https://github.com/dlech/KeeAgent/blob/master/CHANGELOG.txt

Latest documentation: https://keeagent.readthedocs.io/en/latest/

**Comment by dlech** [comment]
I updated readthedocs.org to show the version number by default, so I hope this resolves the issue.
