### ISSUE TITLE
Releases not consistent naming

### ISSUE THREAD

**Issue by pauby** [dlech/KeeAgent#276]
For newly released versions can you please release them using the same file naming scheme? For 0.10.1 you releases `KeeAgent_v0.10.1.zip` but version 0.11.1 is just the plgx file.

Trying to keep the [Chocolatey package](https://chocolatey.org/packages/keepass-plugin-keeagent) up to date without manual intervention is difficult without consistent naming.

Thanks.

**Comment by dlech** [comment]
Sorry, I haven't had time to do it right. Zip files are available at https://lechnology.com/software/keeagent/.

**Comment by dlech** [comment]
Did I do it right this time? (v0.11.4)

**Comment by pauby** [comment]
I apologise for the HUGE delay in responding to this. I've just pushed v0.12 to Chocolatey and if you keep the consistent naming and releases as you have for that, it will automate the package creation process.

Many thanks!

**Comment by Sieboldianus** [comment]
`v0.13.1` is out but, again, unfortunately, no automatic release in choco.

I guess it is the naming scheme again:
- v0.13.1 (2022-07-17) `[KeeAgent.plgx.zip](https://github.com/dlech/KeeAgent/releases/download/v0.13.1/KeeAgent.plgx.zip)`
- v0.12.1 (2020-08-31) [KeeAgent_v0.12.1.zip](https://github.com/dlech/KeeAgent/releases/download/v0.12.1/KeeAgent_v0.12.1.zip)

**Comment by pauby** [comment]
@Sieboldianus If the file naming convention has changed again then that is most likely the issue.

**Comment by dlech** [comment]
Sorry, that wasn't intentional. Are you pulling releases from Github or lechnology.com?

**Comment by pauby** [comment]
It's checking [GitHub releases](https://github.com/pauby/ChocoPackages/blob/master/automatic/keepass-plugin-keeagent/update.ps1#L5).

**Comment by dlech** [comment]
I have updated the file name.

**Comment by pauby** [comment]
Awesome. Thank you! It should pick that up at the next run. I'll keep an eye out for it.

**Comment by pauby** [comment]
New version has now been [approved on Chocolatey Community Repository](https://community.chocolatey.org/packages/keepass-plugin-keeagent/0.13.1).
