### ISSUE TITLE
Make it compatible with KeePass 2.43+

### ISSUE THREAD

**Issue by magneval** [dlech/KeeAgent#281]
on this page https://lechnology.com/software/keeagent/ it is said «Not compatible with KeePass 2.43+» since September 11, 2019
I've upgrade to the latest KeePass, and I miss KeeAgent.

**Comment by dlech** [comment]
Duplicate of #265

**Comment by magneval** [comment]
thank you

Le lun. 30 sept. 2019 à 15:27, David Lechner <notifications@github.com> a
écrit :
