### ISSUE TITLE
Empty menu items with beta version

### ISSUE THREAD

**Issue by gusowski1** [dlech/KeeAgent#283]
I have today installed the latest beta version of keeagent 0.11.3
I some empty menue items.
In "Group" there is an empty menue item.
In "Entry" there is an empty menue item.

**Comment by dlech** [comment]
Can you post a screenshot to show what you mean?

**Comment by gusowski1** [comment]
Sure.
![image](https://user-images.githubusercontent.com/6065608/66706344-87db7e00-ed31-11e9-97df-295e5759fe9d.png)

**Comment by bstoots** [comment]
I'm encountering the same issue.  Also when I click the KeeAgent menu option under Entry KeePass crashes.

My setup:
* Ubuntu 16.04
* KeePass 2.43 (built from source)
* KeeAgent 0.11.3 (built from source)
* Mono: mono-complete:amd64/xenial 6.4.0.198-0xamarin3+ubuntu1604b1 uptodate

If I also build KeePass 2.43 from source and run it with Mono I encounter the following trace when attempting to open the KeeAgent menu:  https://gist.github.com/bstoots/6049b450fce8d1052fe448d7a765f935.

I cloned the repo and built the plugin manually using VS Code and noticed the following errors in the debugger:

Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [KeeAgent]
Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [SshAgentLib]
Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [SshAgentLib.Ui.WinForms]

I'm not sure what debug information may be useful or relevant to you.  Let me know if I can provide anything else.

**Comment by madburg** [comment]
Same for Windows 7

KeePass 2.43
KeeAgent 0.11.1

![image](https://user-images.githubusercontent.com/2113383/71776098-85b44480-2f59-11ea-8a91-02b37196b071.png)

**Comment by mrazekpetr** [comment]
Same problem with:

Windows 10 (1909)
KeePass 2.44
KeeAgent 0.11.1

KeePass not crashing on menu item click, but crash with Keystroke Ctrl+M/Ctrl+Shift+M.

**Comment by dlech** [comment]
Fixed in v0.11.4
