### ISSUE TITLE
Problems with referenced password

### ISSUE THREAD

**Issue by coucoy** [dlech/KeeAgent#286]
Hi, using Kee for firefox under windows with KeeAgent.
If i have a website that uses reference : {REF:U@I:...}; it inputs the references string instead of resolving to the actual passwords.

**Comment by dlech** [comment]
Are you saying that KeeAgent breaks Kee and that Kee works as expected if KeeAgent is not installed?

**Comment by coucoy** [comment]
No, sorry, i wasn't totally awake when i made the issue.
There is nothing wrong on KeeAgent.
