### ISSUE TITLE
Trying to understand how auto key detection works when log in

### ISSUE THREAD

**Issue by Draghmar** [dlech/KeeAgent#293]
Hi
I'm using KeeAgent 0.11.1.0 in Agent mode with KeePass 2.43 in portable edition on Windows 10. I have a few keys imported into KeePass that are automatically used when I log in with putty. Those keys where somehow detected when I first used them and imporeted. Not sure how though...
Now I wanted to add manually new key that I generated myself. It is imported into KeeAgent but when I try to log in with putty it doesn't use it like other keys. The key itself works. Also if I install one of the previous keys on the server it actually detects log in attempt.
I don't understand why it doesn't work with this new key. I can't find info about how auto detection works so I don't know what I could done wrong. Help? ;)

**Comment by dlech** [comment]
How many keys are loaded in the agent at the same time? It is common for remote servers to restrict the number of keys that it looks at (usually to 6).

**Comment by Draghmar** [comment]
Only 4 with this new one. I know that those older ones are working. Is there a way to change order of keys that agent asks server? How can I check this limit?

**Comment by Draghmar** [comment]
Ok...now I don't get it at all. It worked. And the only thing that actually happened from previous attempts is the fact that day passed so KeePass (and KeeAgent as a result) are freshly started.
