### ISSUE TITLE
Use HTTPS in UpdateUrl()

### ISSUE THREAD

**Issue by r15ch13** [dlech/KeeAgent#299]
Let's Encrypt is enabled on https://updates.lechnology.com/ so why not use it? :smile:
https://github.com/dlech/KeeAgent/blob/ab27fde6bdeba945a4d4f1942e76caf1bf34d94f/KeeAgent/KeeAgentExt.cs#L252-L254

**Comment by dlech** [comment]
This has been implemented since https://github.com/dlech/KeeAgent/commit/158a8d0eb82e22f67088b9235dcd6d29f1605fb9.
