### ISSUE TITLE
Why is the KeyAgent.settings automatically  attached? Is that normal?

### ISSUE THREAD

**Issue by hahaleyile** [dlech/KeeAgent#303]
![image](https://user-images.githubusercontent.com/38727644/88547469-634a5b80-d050-11ea-9dd6-e8c6a7662bc1.png)

**Comment by dlech** [comment]
This is needed to store entry-specific settings for the KeeAgent extension. It is normal for any entry that has the "Allow KeeAgent to use this entry" box checked.
