### ISSUE TITLE
Fedora 33 - RSA keys are still signed with SHA-1 (ssh-rsa) instead of SHA-256/SHA-512

### ISSUE THREAD

**Issue by wiesl** [dlech/KeeAgent#308]
Hello,

With Fedora 33 SHA-1 (ssh-rsa) don't work anymore. 

KeeAgent (or Kitty latest?) still signs with SHA-1 instead of the better SHA-256.

According to the release notes that should work. Logs on the server say they get ssh-rsa.
https://github.com/dlech/KeeAgent/blob/master/debian/changelog
* Add support for SHA-256 and SHA-512 RSA key signing

Ideas?
Looks like a bug in KeeAgent or Kitty/Putty.

Thnx.

**Comment by dlech** [comment]
Support for this was added several years ago in https://github.com/dlech/SshAgentLib/commit/22a1261a3c87472b2e9a13019d417bd87ad1d929.
