### ISSUE TITLE
SSH agent forwarding

### ISSUE THREAD

**Issue by bug-ware** [dlech/KeeAgent#311]
With native OpenSSH of Windows 10 (version 8.1) I'm using agent forwarding to a ssh session.

I tried using KeeAgent as agent + native Windows SSH client (experimental support) and the connection is established using KeeAgent according to the notification, however, ```$SSH_AUTH_SOCK``` is not set in the ssh session and forwarding is not working

I also tried using *KeeAgend as client* to the native OpenSSH Windows 10 agent (ssh-agent).  But this is not suported. See #255. BTW: Any news on this?

Finally, I tried KeeAgend as agent + ```wsl-ssh-pageant-amd64-gui.exe  --systray --winssh ssh-pageant``` and ```set SSH_AUTH_SOCK=\\.\pipe\ssh-pageant```, again the connection is established and notification says that wsl-ssh-pageant-proxy is used. But  ```$SSH_AUTH_SOCK``` is again not set in the ssh session.

Maybe I'm doing something wrong? Otherwise, I would lve to see this feature. Thanks!

**Comment by bug-ware** [comment]
Sorry! My fault... first method and third method are both working...

However, any news on KeeAgent as client to Windows OpenSSH ssh-agent (#255). This would be a zero config solution.

Best regards.

**Comment by dlech** [comment]
It sounds like this issue is resolved.
