### ISSUE TITLE
ssh.exe problem with keeagent 

### ISSUE THREAD

**Issue by madejusz** [dlech/KeeAgent#315]
Issue:
ssh.exe can't get access to ssh keys
C:\Users\test123> ssh-add -l
error fetching identities: invalid format
C:\Users\test123>

Software version:
 OS: Win10
 ssh -V: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
 Keepass: 2.48 (64bit)
 KeeAgent: 12.1

Configuration of KeeAgent:
Cygwin/MSYS is set
Enable agent for windows OpenSSH (experimental) - is on

Tested with SSH_AUTH_SOCK set to Cygwin socket and msysGit. Without success.

Putty.exe working pretty well.

**Comment by madejusz** [comment]
Keys created by ssh-keygen -t ed25519, attached to Keepass and loaded into agent. Work fine from Linux (and even under WSL v1/v2 with socat/npiperelay.exe trick). Putty.exe can read it to... but openssh-client from Win10 can't.

**Comment by dlech** [comment]
OpenSSH 7.7 was released April 3, 2018, so it probably can't handle keys that use newer formats. As a workaround you can change the keys to a different format that is supported by that version of OpenSSH or set the problematic keys to not load automatically.

Windows 11 has OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2, so hopefully this won't be a problem for most users going forward.

This isn't something we can fix in KeeAgent, so closing the issue.

**Comment by theking2** [comment]
For what is't worth on Windows 10 the output of `ssh -V` is

```
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```
