### ISSUE TITLE
Not compatible with KeePass 2.48.1

### ISSUE THREAD

**Issue by CruzMarcio** [dlech/KeeAgent#317]
After updating to 2.48.1 I'm getting this error when loading KeePass:
Already tried clearing the PluginCache folder

![image](https://user-images.githubusercontent.com/40072316/119577138-6efdd000-bd90-11eb-8922-5683240cb4be.png)

**Comment by dlech** [comment]
Are you using an older .NET runtime, like 3.5? Is something wrong with [KeePass.exe.config](https://github.com/dlech/KeePass2.x/blob/VS2019/Ext/KeePass.exe.config)?

**Comment by CruzMarcio** [comment]
There was no KeePass.exe.config file on my installation but I created the file with the content of the file you sent and it works fine now. Thanks.
