### ISSUE TITLE
agent mode gui buttons extremely wide

### ISSUE THREAD

**Issue by dmerillat** [dlech/KeeAgent#318]
Running on linux, keyagent 0.12.1.0 on keypass 2.47, the button widths are enormous.  I've got dual 1440p monitors and it stretches across 2/3rds of my screen to show all the buttons.

I'm not sure if it's trying to optimize for 2/3 of a screen and getting confused by the dual monitors, I haven't tried on a single-screen setup.  As you can see even this screenshot isn't wide enough: the final button is cropped off unless I make the window even wider.

This problem is the same with keys loaded, I removed them to test if they were causing the issue before taking the screenshot.

![gui-weirdness](https://user-images.githubusercontent.com/9002752/123165384-29412f80-d442-11eb-9662-872899fe33c7.png)

**Comment by dlech** [comment]
What is the operating system and version?

**Comment by dlech** [comment]
The buttons have been removed (replaced with toolbar) so this is no longer applicable.
