### ISSUE TITLE
Force to empty key list

### ISSUE THREAD

**Issue by vigi86** [dlech/KeeAgent#319]
I ran into an issue where I am not able to remove the keys from the KeyAgentManager. **Remove** button does nothing and **Remove All** throws an unhandled exception:
![image](https://user-images.githubusercontent.com/8401847/124735904-c3ab7380-df16-11eb-8fd5-ae0f49d11805.png)

Readding the keys shown in the list gives no feedback, like it has add the key to the list. 
While there are two other keys where I get this message:
![image](https://user-images.githubusercontent.com/8401847/124736510-5cda8a00-df17-11eb-9feb-04e2fb77d918.png)

I have the newest versions of KeePass (2.48.1) and KeeAgent (0.12.1).

**Is it possible to force empty the list?** I checked the OpenSSH agent, there was nothing loaded, stopped the service, but still nothing... Is there a local file with those information stored? Thanks!

**Comment by dlech** [comment]
Can you provide a test .kdbx file that reproduces the issue?

**Comment by dlech** [comment]
Closing due to no response.
