### ISSUE TITLE
KeeAgent unable to process Putty PPK v3 file format

### ISSUE THREAD

**Issue by p-doyle** [dlech/KeeAgent#320]
Starting at Putty 0.75 Puttygen started using [PPK format v3](https://tartarus.org/~simon/putty-snapshots/htmldoc/AppendixC.html#ppk-old) when exporting a private key.  KeeAgent fails to load the .ppk file with an error 'Unknown file format'.  The only difference between v2 and v3  seems to be the algorithm used to generate the Private-MAC value.  The ppk output version can be changed in puttygen under Key -> "Parameters for saving key files..." so this can be worked around but was wondering if support for the v3 file format could be added to KeeAgent in the future?

**Comment by dlech** [comment]
Duplicate of #316?

**Comment by p-doyle** [comment]
Doh, sorry about that, didn't search hard enough...
