### ISSUE TITLE
Pass custom/proxy name (using process)

### ISSUE THREAD

**Issue by strarsis** [dlech/KeeAgent#327]
As for some implementations helper tools have to be used (as [`wsl-ssh-agent`](https://github.com/rupor-github/wsl-ssh-agent)), 
it would be very helpful if KeeAgent would allow the process that requests the key to pass a custom process name.
Currently the process that is using the key is always `npiperelay` when WSL 2 is used with these extra helper tools.
When `npiperelay` can pass the underlying process name, e.g. `ssh` it would be possible for the user to actually identify the underlying requesting process,

Related: https://github.com/rupor-github/wsl-ssh-agent/issues/28

**Comment by dlech** [comment]
It looks like the related issue was closed, so closing here too since this won't work without cooperation from the bridge. I agree that unless this is added to the ssh agent spec, it probably isn't worth pursuing.
