### ISSUE TITLE
Move KeePass in GitHub

### ISSUE THREAD

**Issue by Neustradamus** [dlech/KeeAgent#330]
Hello @dlech,

We are now in the future, it is possible to move KeePass in GitHub like other projects?

There is a "Move" feature to inform people the new place...

With this, there will be a better development.

Thanks in advance.

**Comment by dlech** [comment]
Answered at https://sourceforge.net/p/keepass/bugs/2123/

**Comment by Neustradamus** [comment]
@dlech: Thanks for your reply!

The original request is very old:
- https://sourceforge.net/p/keepass/discussion/329221/thread/97110c29/

The world changes, ...

Time to move like all other projects...
