### ISSUE TITLE
Featurerequest - use URL to filter key to use

### ISSUE THREAD

**Issue by nettyjump** [dlech/KeeAgent#336]
Hi guys

Would it be possible to use the URL-entry to use the specific private key for authentication instead of iterating thorugh all keys? It would resolve the issue of "too many authentication failures" when using a lot of private keys. I have currently set the option "Show key selection dialog when ..." to resolve this issue..

**Comment by dlech** [comment]
No, the agent doesn't have any way to know what server is making the request. The "official" SSH solution is to use the `IdentityFile` feature to map keys to hosts.

**Comment by nettyjump** [comment]
Thank you for your response I will look into that.
