### ISSUE TITLE
Document WSL2 workaround

### ISSUE THREAD

**Issue by dlech** [dlech/KeeAgent#339]
The WSL socket option from #321 only works with WSL1 and not WSL2 due to https://github.com/microsoft/WSL/issues/5961.

https://github.com/rupor-github/wsl-ssh-agent#wsl-2-compatibility contains a fairly simple workaround to bridge the Windows OpenSSH socket to WSL2 instead.

**Comment by strarsis** [comment]
@dlech: Is this guide still applicable? https://gist.github.com/strarsis/e533f4bca5ae158481bbe53185848d49

**Comment by dlech** [comment]
It says that it was just updated this month, so I would guess so.

**Comment by dlech** [comment]
Even simpler workaround: just type `ssh-add.exe` instead of `ssh-add` and `ssh.exe` instead of `ssh` to use Windows OpenSSH.

If you don't want to type `.exe` or need it for something scripted, then create symlinks from ` /mnt/c/Windows/System32/OpenSSH/*.exe` to `/usr/local/bin/*` where `*` is any of `ssh`, `ssh-add`, `scp`, `sftp`.
