### ISSUE TITLE
How can I check KeeAgent is running

### ISSUE THREAD

**Issue by mgrulich** [dlech/KeeAgent#340]
I need to check the KeeAgent (or another like Pagent) is currently running (and maybe available) on Windows any suggestions on how can I do this?

**Comment by msabatier** [comment]
Hi,

May be you can use command `ssh-add -l` with any ssh agent to see if connection to the agent is successful and if there are any keys loaded.

**Comment by dlech** [comment]
I agree that the best way is to just try to connect to the agent somehow.
