### ISSUE TITLE
after first successful ssh command agent stops functioning

### ISSUE THREAD

**Issue by dten** [dlech/KeeAgent#349]
I upgraded to the latest keeagent hoping to solve some intermitted issues I was getting which I suspected might be #338 

but now after the first usage of a key the agent stops working until i restart keepass. i didn't change anything else except upgrade keeagent

![image](https://user-images.githubusercontent.com/1019038/181238142-af5bdd78-66b0-483d-ae62-c23e593707ee.png)

i'm using from wsl2 via socat.
https://gist.github.com/strarsis/e533f4bca5ae158481bbe53185848d49

how can i debug this?

**Comment by dten** [comment]
well the steps are basically in that screenshot. i have keeagent set up as per the wsl2 instructions linked. i have keys added from keepass entries. the database is unlocked and i run the commands in the screenshot. the only mystery bit would be that the location ssh'd to used one of the keys.
visual studio is a good idea though :) sounds like a good start

**Comment by dten** [comment]
so i have it running debug in vs code

i get this error logged every time i `ssh-add -l` before it's broken
![image](https://user-images.githubusercontent.com/1019038/181477491-a36f1fdf-f71c-4811-80a6-00c5fdebb1e4.png)

i get this on the first `ssh` command
![image](https://user-images.githubusercontent.com/1019038/181477648-47016770-c1cc-4e76-a416-cd9869d78d50.png)


afterwards repeating those commands logs no errors but does not work

**Comment by dten** [comment]
i checked out 8dba6e61e7bc533ba6d2c4732699a0a6d747dbc9 and i don't get errors. i will bisect later to find out where it breaks

**Comment by mplattner** [comment]
I experience the same problem.

**Comment by dten** [comment]
bisect result says

```
81fec50ce909f80f35087194e09ac512e3223bf5 is the first bad commit
commit 81fec50ce909f80f35087194e09ac512e3223bf5
Author: David Lechner <david@lechnology.com>
Date:   Fri Jan 28 20:45:34 2022 -0600

    update SshAgentLib submodule

 SshAgentLib | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by dten** [comment]
hmm i have `81fec50ce909f80f35087194e09ac512e3223bf5` checked out and i have the sshlib submodule checked out at `55ffc83ec060e6c24b58dd2075a768838a2010c8` and it is broken, if i move the submodule one commit earlier then it works again.

this fits with it being related to the windows open ssh impl

**Comment by dten** [comment]
the problem seems to be `GetProcessById` is throwing and so killing the loop that sets up new servers. it throws in the code before that commit but its in a try catch

![image](https://user-images.githubusercontent.com/1019038/183309790-2fbc66b9-c411-4fd6-8337-d96f4c0a6da7.png)

**Comment by dlech** [comment]
Is this still a problem with [v0.13.2](https://github.com/dlech/KeeAgent/releases/tag/v0.13.2)?

**Comment by mplattner** [comment]
I've just tested v0.13.2. It does work now to create multiple direct ssh sessions after another, i.e., by executing `ssh <host>` in multiple terminal windows.
However, when creating a nested session using agent forwarding (using `ssh <host>` within an existing SSH session), the "ssh key is being used"-notification pops up, but then the creation of the connecting hangs. This does work with v0.12.1 without problems.

**Comment by dlech** [comment]
Can you please start a new issue for the new problem with exact steps needed to reproduce the problem?

**Comment by mplattner** [comment]
Sure. Please see #362.

**Comment by dlech** [comment]
> the problem seems to be `GetProcessById` is throwing and so killing the loop that sets up new servers

This was fixed in https://github.com/dlech/SshAgentLib/commit/c96e6d00af3198980f73c8bdcd9dc7f58afa0f57

**Comment by dten** [comment]
thank you for this and the concurrent requests fix 🥳
