### ISSUE TITLE
0.13.1 - Can not select attachment for new entry

### ISSUE THREAD

**Issue by egfx-notifications** [dlech/KeeAgent#351]
When adding a new entry to KeePass I can no longer activate a key attachment for KeeAgent 0.13.1 as the attachment selection dialog is missing, probably either behind the constraints table or further down below, but not accessible through a scrollbar

Using KeePass 2.47 (64-bit) on Windows 10

![Screenshot 2022-07-28 160654](https://user-images.githubusercontent.com/68847951/181525736-dd577de8-be8e-4300-90aa-25099075933a.png)

**Comment by ChristianGfK** [comment]
Works as expected here, with KeePass 2.52:
![image](https://user-images.githubusercontent.com/6390522/189589680-267cb01c-a1a3-4fee-a3ec-61ebacc55da5.png)

I notice your UI looks very large, are you using UI scaling?
You could try setting it to 100% and see if that helps at all, as a workaround.

**Comment by egfx-notifications** [comment]
I do. I just tried again without UI scaling and I also tried going down from 4K to HD resolution. Finally I tried using the current KeePass release instead of the older version my employer supplies. Unfortunately it still always looked like in my first screenshot.

**Comment by egfx-notifications** [comment]
Ok, looking at the code I am a bit confused why the DataGriedView has its Anchor set to `Top, Bottom, Left, Right`. I'd say `Top, Left` would be sufficient.
Interestingly there is a commit (https://github.com/dlech/KeeAgent/commit/bef5a0d2d6094103075bba28c2c3c28370d6bc1c) setting the Anchor to `Top, Left` if Mono is used and the commit says it is to prevent the view from displaying over other controls, so that sounds exactly like the problem I have here.
I assume that here on Windows 10 the .NET Framework would be used, but maybe the issue is identical to the one in Mono?

**Comment by ChristianGfK** [comment]
You could try forking, changing that, and using the GitHub actions (do they get forked as well?) to build a new .plgx.
(I say that as if I had done it before, which I have not. :P)

**Comment by egfx-notifications** [comment]
You got a point there. Was reading up on what I have to get to build locally, but let's see if GitHub actions work.

**Comment by egfx-notifications** [comment]
Yes, I had to manually activate the GitHub Actions in my fork in order to confirm that I read and understood the workflows that would be run under my account, so did that and it worked. And the fix worked as well, so hoping for the PR to get merged :)

**Comment by SugoiDev** [comment]
I can confirm the issue happens on Windows 11 with kp 2.52 and no display scaling.
I don't frequently add new keys, so I'm unsure when this started happening.


![image](https://user-images.githubusercontent.com/7355630/189905821-68de0483-5a5b-4f42-9d11-29b773f85009.png)

**Comment by egfx-notifications** [comment]
> I can confirm the issue happens on Windows 11 with kp 2.52 and no display scaling. I don't frequently add new keys, so I'm unsure when this started happening.
> 
> ![image](https://user-images.githubusercontent.com/7355630/189905821-68de0483-5a5b-4f42-9d11-29b773f85009.png)

Great, someone else with this issue :D

Can you test again with [this](https://github.com/dlech/KeeAgent/suites/8242428324/artifacts/360584508) version including [my PR](https://github.com/dlech/KeeAgent/pull/356)?

**Comment by ziesemer** [comment]
> Can you test again with [this](https://github.com/dlech/KeeAgent/suites/8242428324/artifacts/360584508) version including [my PR](https://github.com/dlech/KeeAgent/pull/356)?

I can confirm that it fixed the UI issue for myself as well.  I did test your updated version, but ran into other issues with KeeAgent - which I fully expect are unrelated to your fix, but going from 0.12.1 to 0.13.1 - or possibly, something in the build process itself.  Specifically, I was no longer able to load existing PPK keys into the running agent.  I'll try to narrow this down further yet sometime today and report back.

**Comment by SugoiDev** [comment]
> Can you test again with [this](https://github.com/dlech/KeeAgent/suites/8242428324/artifacts/360584508) version including [my PR](https://github.com/dlech/KeeAgent/pull/356)?

Just tested and it looks good.
Thanks for the PR!
