### ISSUE TITLE
Pleasant Password Server compatibilty 

### ISSUE THREAD

**Issue by Shayano** [dlech/KeeAgent#352]
Hi, unfortunately I didn't see a discussion area so I'll leave my question here.

Is it possible to make the latest versions of KeeAgent compatible with older versions of Keepass with a little development knowledge? Pleasant Password Server use a modified Keepass client to connect to. Currently it is version 2.39.1

KeeAgent works in lab but it requires to use version 0.10.1.0 and putty/puttygen in version 0.74 and it sometimes creates some crashes when using right click on entries.

Have there been any changes in the way plugins work on Keepass making it difficult to adapt to older versions ?

Sorry if my question seems naive, I have no idea of the implications.
Thank you in advance for your possible answers.

**Comment by dlech** [comment]
Support for this is not planned.
