### ISSUE TITLE
keepass update check do not find latest KeeAgent release

### ISSUE THREAD

**Issue by gpion** [dlech/KeeAgent#353]
![image](https://user-images.githubusercontent.com/2971216/184099691-3679951b-052d-4d8d-8b94-d2a56823d40a.png)

**Comment by ChristianGfK** [comment]
https://updates.lechnology.com/KeePassPlugins needs a little love, I guess. [That's where it checks.](https://github.com/dlech/KeeAgent/blob/892ec49b73a1a1d80e7e6a4cd1ddfe6e102add30/KeeAgent/KeeAgentExt.cs#L246)

**Comment by dlech** [comment]
This has been updated for v0.13.2.
