### ISSUE TITLE
WSL compatible socket file not working

### ISSUE THREAD

**Issue by skupr** [dlech/KeeAgent#357]
I've tried to use a recently added KeaAgent option "Create WSL compatible socket file", but failed to get it working.

KeeAgent options:
![image](https://user-images.githubusercontent.com/783636/190891830-24509ddd-1f4a-4b63-a1a8-822df256a90a.png)

Here's how it looks like from the WSL console:
```
$ export SSH_AUTH_SOCK=/mnt/d/.ssh-agent-wsl.socket
$ ssh-add -l
Error connecting to agent: Connection refused
$ ls -l /mnt/d/.ssh-agent-wsl.socket
-rwxrwxrwx 1 stask stask 0 Sep 18 14:53 /mnt/d/.ssh-agent-wsl.socket*
```

KeePass version: 2.52
KeeAgent version: 0.13.1.0
Windows version: Windows 10 Pro
WSL2 - Ubuntu 22.04

Can you please help me with setting it up?

**Comment by dlech** [comment]
It only works with WSL1.  Also see #339.

**Comment by skupr** [comment]
@dlech thank you!
I would then suggest to explicitly label this option in UI that this is for WSL version 1. This may prevent users from confusion and avoid having more duplicate issues in GitHub )
