### ISSUE TITLE
Agent connection drops

### ISSUE THREAD

**Issue by a-m-s** [dlech/KeeAgent#359]
I'm using the Windows OpenSSH agent (agent mode) on Windows (together with the npiperelay trick for WSL2, but I can also see the issue with the Windows ssh-add command).

When KeePass is first started KeeAgent works well, but sometime later I find that it doesn't respond anymore:

```
C:\Users\astubbs>ssh-add -l
Error connecting to agent: No such file or directory
```

Possibly this is related to machine locking or sleeping or something, but I've not confirmed this.

It would be nice if the agent did not do this, or could auto-restart when it does, but if that's not easy then a restart button in KeePass would be better than having to quit KeePass and reopen and reunlock every time.

**Comment by dlech** [comment]
Is this still a problem with (v0.13.2)[https://github.com/dlech/KeeAgent/releases/tag/v0.13.2]?

**Comment by a-m-s** [comment]
I'm still waiting for 0.13.2 to install via Chocolatey..... will let you know when I've had it a week or so.

**Comment by dlech** [comment]
Hopefully same issue as #362
