### ISSUE TITLE
Allow user to select a single SSH key when a list of keys is requested by a client program

### ISSUE THREAD

**Issue by xchs** [dlech/KeeAgent#38]
Would you consider adding an additional option to the KeeAgent plugin settings to enable/disable the KeeAgent behavior and interaction for a multiple SSH key request?

That said, the plugin should pop up a dialog box when a list of SSH keys is requested that will let you choose which keys are fetched.

For instance, it could be useful for (developing) environments with multiple identities (work / private) and therefore different SSH keys for each of them.

In the meantime, thank you very much!

**Comment by dlech** [comment]
Based on the discussion in #90, I am reopening this issue. I think there is more of a need for this that I thought.

**Comment by dlech** [comment]
I've made an attempt to implement this feature. Let me know how it works for you.

http://lechnology.com/2015/07/keeagent-beta-v0-7-4-released/

**Comment by dlech** [comment]
Please open a new issue for any problems or further enhancements.

**Comment by addshore** [comment]
I'd just like to say that I just ran into this issue when using ProxyCommand!

Previously the first key retrieved would be correct, the second key would then for some reason be incorrect thus my ProxyCommand would never succeed.

I am on 0.7.5 now and I assume the option you are talking about is the "show key selection dialog" which I am now using to solve my issue above with ProxyCommand and it works a treat!
