### ISSUE TITLE
Missing Build in PPA Repo

### ISSUE THREAD

**Issue by florian-asche** [dlech/KeeAgent#380]
Hi,

i was just wondering, the Version  v0.13.1 is released but there is no corresponding version in the ubuntu ppa.

Regards Florian

**Comment by dlech** [comment]
The KeePass 2.x and Mono packages haven't received any updates in several years and The `keepass2` package has been removed from Debian entirely, so I have decided it isn't worth the effort any more to maintain the PPA.

**Comment by florian-asche** [comment]
There is no more KeeAgent for Linux?

**Comment by dlech** [comment]
It still works on Linux, just no PPA install method.

**Comment by florian-asche** [comment]
But is there some special build for Linux or is it the same file?

**Comment by dlech** [comment]
It is the same file.

**Comment by florian-asche** [comment]
Ah okay, i always had the feeling that it is a special compiled version. I did try to load the latest version with KeePass and it tells me, that the .net version is outdated.

**Comment by dlech** [comment]
You need KeePass >= 2.52 or the workaround described in https://github.com/dlech/KeeAgent/issues/343.

**Comment by jefferyto** [comment]
There are still packages in [Debian](https://packages.debian.org/search?keywords=keepass2) and [Ubuntu](https://packages.ubuntu.com/search?keywords=keepass2), and there is an [unofficial PPA](https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/keepass2) with more up-to-date versions. It would be great if the KeeAgent PPA can be revived :pray:
