### ISSUE TITLE
What is the alternative to "Save attachment to temporary file when key is loaded"

### ISSUE THREAD

**Issue by j54j6** [dlech/KeeAgent#383]
Hi, 

I want to use this Plugin and currently I setup the Plugin for use with Putty. 
I've read the readthedocs site but can't find an explanation when I need to use the "temporary file" option - is this more secure? - I've read that the file will not be deleted when keepass crashes.. - how does the normal way work? - if I keep the box for saving to a temporary file unchecked?

Thanks for your help :)

**Comment by dlech** [comment]
This feature is only needed if you need the private key file to use as an argument for the `-i <identity_file>` option of of `ssh`. People generally need this feature to specify that a connection should use a specific key. If you don't have a reason to do this, then you don't need the feature.

**Comment by j54j6** [comment]
Hey :)
thank you for the quick response ^^
I need KeeAgent for exactly this reason - I want to link my private key and hand it over to Putty SSH - So I think I need to enable this option.

Is this in any way unsecure? - I've tested this already and I didn't need to paste my password - KeeAgent also do this...

**Comment by dlech** [comment]
It is as secure as the encryption of the private key file.
