### ISSUE TITLE
Support for EdDSA Ed448 (448 bits)

### ISSUE THREAD

**Issue by Speed4Trade-Admin** [dlech/KeeAgent#388]
With putty key generator it is possible to generate keys with EdDSA and using the curve Ed448  (which uses SHA-3).
Unfortunately, I get the error message "unknown algorithm" when trying to load the key into keeAgent.

Is it possible to support this algorithm?

**Comment by dlech** [comment]
I fixed the missing parts of the implementation so Ed448 keys will load now. However, I'm not aware of any servers that support this to validate that authentication actually works.

You can grab the build from https://github.com/dlech/KeeAgent/actions/runs/5373113634 for testing.
