### ISSUE TITLE
KeeAgent issue after upgrading KeePass to 2.54/2.55

### ISSUE THREAD

**Issue by rtmonagh** [dlech/KeeAgent#398]
I recently tried to upgrade KeePass from 2.53.1, but when I brought it back up after the upgrade I got the error in the screenshot below. I have KeeAgent 0.13.5.0 and I tried it with both KeePass 2.54 and 2.55.  Going back to 2.53.1 works.

![image](https://github.com/dlech/KeeAgent/assets/101229260/4a65c2c2-9c7f-43cf-a10f-0d92305edde3)

**Comment by dlech** [comment]
Operating system and version? .NET version?

Does it make a difference if you clear the plugin cache?
