### ISSUE TITLE
Minor docs correction is needed in the Installation description

### ISSUE THREAD

**Issue by rakoczy** [dlech/KeeAgent#401]
In the Installation section of the documentation for  Windows, the Note for point 3 contains the text:
"**If you used the Windows installer to install KeePass, then the folder will be 
_C:\Program Files (x86)\KeePass Password Safe 2\Plugins_ (or 
_C:\Program Files\KeePass Password Safe 2\Plugins_ on 32-bit systems).**"
Paths are swapped.

**Comment by dlech** [comment]
Actually, I think more recent versions of KeePass changed the install directory. But needs update nonetheless.
