### ISSUE TITLE
error 404 when trying to download 0.13.7 release

### ISSUE THREAD

**Issue by gpion** [dlech/KeeAgent#409]
Link from the home page  https://lechnology.com/wp-content/uploads/2024/04/KeeAgent_v0.13.7.zip
leads to : 
![image](https://github.com/dlech/KeeAgent/assets/2971216/e3762a24-3f9d-413e-99e2-44e014205032)

**Comment by dlech** [comment]
Oops. Thanks for letting me know. Should be fixed now.

Correct link is: https://lechnology.com/wp-content/uploads/2024/05/KeeAgent_v0.13.7.zip
