### ISSUE TITLE
Upgrading KeeAgent from v0.13.6 to v0.13.7 breaks KeePass on Linux/FreeBSD/Haiku/ReactOS with Mono 6.8.0.105+dfsg-3.4

### ISSUE THREAD

**Issue by tps800** [dlech/KeeAgent#410]
Upgrading KeeAgent from v0.13.6 to v0.13.7 breaks KeePass on Linux/FreeBSD/Haiku/ReactOS with Mono 6.8.0.105+dfsg-3.4

KeePass won't be able to open any window except database open password dialog.
The database itself won't be opened, after entering the database passphrase.
Keepass reacts on queries by KeePassNATMsg or KeePassHTTP, but never find a match.
Rolling KeeAgent back to v0.13.6 restores KeePass working to normal.

**Comment by tps800** [comment]
![Bildschirmfoto_2024-05-05_10-10-46](https://github.com/dlech/KeeAgent/assets/702156/29f0cf6a-81d7-43c8-864c-51734a21ec78)

[mono.txt](https://github.com/dlech/KeeAgent/files/15212130/mono.txt)

**Comment by dlech** [comment]
Can you please test https://github.com/dlech/KeeAgent/actions/runs/8960600593 to see if this is fixed for you?

**Comment by tps800** [comment]
Yes. It fixes it.
