### ISSUE TITLE
Clicking 'No' when adding keys

### ISSUE THREAD

**Issue by theking2** [dlech/KeeAgent#419]
When adding key files where one is already there shows a dialog with three options:
![afbeelding](https://github.com/user-attachments/assets/de85f59a-8631-47b7-8e66-0622682bdc27)

option 'Yes' renames the existing attachement and creates a new one
option 'Cancel' does nothing
option 'No' does nothing

With option 'No one would expect either the existing attachement being use or the existing attachement bein replaced with the new one as is per description.

**Comment by dlech** [comment]
I think this is a KeePass dialog, not a KeeAgent dialog.

KeeAgent just uses the existing attachment feature in KeePass and doesn't add anything extra there.

**Comment by theking2** [comment]
> I think this is a KeePass dialog, not a KeeAgent dialog.
> 
> KeeAgent just uses the existing attachment feature in KeePass and doesn't add anything extra there.

You probably are right here.
