### ISSUE TITLE
Extending the confirmation dialog

### ISSUE THREAD

**Issue by Xuerian** [dlech/KeeAgent#59]
Putting the fixed confirmation dialog in the latest update to good use, I've run into some suggestions.

* Display more information about requesting application. Image name, Window name, something.
 * Not sure how the protocol works, though, so I'm sure it may just be impossible.
* Allow/deny fingerprint access to {this, all} keys for {x minutes, this session, forever}[ for this process|fingerprint] options, perhaps?

**Comment by homes32** [comment]
+1 for Display more information about requesting application. (process/Image name/etc) I actually came here looking to suggest the same enhancement if possible.

**Comment by Ciantic** [comment]
:+1: It's useless now, how do I know if it's malicious application if I don't know which one is requesting?

**Comment by yruslan** [comment]
+1 It would be extremely helpful, at least in Windows. Also additional process information could be helpful in the balloon message.

**Comment by dlech** [comment]
I've added a new feature that displays the information about the requesting application. See <http://lechnology.com/2015/06/keeagent-beta-0-7-1-released/>.

I am closing this issue even though I have not addressed all of the suggestions of the original comment. If you would like to continue discussion of other suggestions or if there are problems with the implementation of the new feature, please open a new issue (one for each problem/suggestion).

**Comment by dlech** [comment]
Hmm... looks like I didn't close this like I said I would. Closing now.
