### ISSUE TITLE
Too many KeeAgent entries in Agent mode fails silently

### ISSUE THREAD

**Issue by MartinWoodhouse** [dlech/KeeAgent#81]
We're using KeePass 0.52 and KeeAgent 0.5.2 on Windows with PuTTY/KiTTY. 

We are storing servers with the username, password (the key passphrase) url (ssh://fqdn:port/) and storing the key as a file attachment, each entry has the following options set in KeeAgent: 
- Allow KeeAgent to use this entry
- Add key to agent when database is opened/unlocked
- Remove key from agent when database is closed/locked

The 'Private Key File Locaton' is then linked as an attachment and the tickbox to 'Save attachment to temporary file when key is loaded' is ticked. 

This has been working fine, today I have added a new server with its own key and passphrase, now none of the entries are working, you click on the URL to open KiTTY/PuTTY and instead of logging you in it loads that key that you expect but then prompts for the passphrase, this seems to be limiting to the number of keys that we have since this affects all servers that we have entered and if we disable any of the entries from auto-loading then it will work. 

This isn't an issue with a server limit with too many logins. It is simply requesting the passphrase (implying one is not successfully loaded from KeeAgent).

I don't know if there might be some arbitrary limit somewhere that we have missed or if we are just doing this wrong.

We don't even need the keys to all load at the start but it would be extra work to manually load a key into KeeAgent each time we want to use it, it would be better if it could automatically just load a key when needed, but I am speaking beyond my own experience here.

**Comment by jportoles** [comment]
For us enabling each key manually for every server each time would be a pain, so we modified PuTTY instead to work around this issue. To fix the memory limitation, in the PuTTY source code change `AGENT_MAX_MSGLEN` defined in `winpgntc.c` and `winpgnt.c` from `8192` to a larger number, e.g. `327680`. Compile, replace your copy of PuTTY, and you are set. This doesn't completely remove the limit, but it should leave enough room for about one thousand keys or so, as opposed to the built in ~30. Figured I'd share in case someone else needs it.
