### ISSUE TITLE
How to choose the correct key (discussion)

### ISSUE THREAD

**Issue by elieux** [dlech/KeeAgent#90]
I want to discuss this because of problems mentioned in #52. I open SSH session directly from PuTTY, rather than from KeePass, so the new features from #81 don't solve my issue.

A) A dialog with the option to choose which key to send to PuTTY seems like the straightforward solution to this problem and also fits nicely with the way auto-type works.

B) However, if there's a way to let KeeAgent decide without user intervention (e.g. with process inspection proposed in #59), I'd rather take that.

C) Does ssh tell ssh-agent which key it wants? Does KeeAgent support ssh-agent protocol? If yes, I could use the "real" ssh instead of plink wrappers for my work in command line and solve at least some of my issues.

**Comment by dlech** [comment]
Picking the discussion back up now that I am 6 months wiser.

> A) A dialog with the option to choose which key to send to PuTTY seems like the straightforward solution to this problem and also fits nicely with the way auto-type works.

I have reopened #38 and will probably implement this. It does indeed seem to be the simplest solution.

> B) However, if there's a way to let KeeAgent decide without user intervention (e.g. with process inspection proposed in #59), I'd rather take that.

I thought that this would not be possible but I was able to use an undocumented system call to find out which process is making the request. So we can at least consider this now. However, this could be rather tricky. For windowed programs, it is not so bad if there is useful information in the window title (like putt.exe), but it probably won't work for command line programs that don't provide any additional information (like plink.exe).

> C) Does ssh tell ssh-agent which key it wants? Does KeeAgent support ssh-agent protocol? If yes, I could use the "real" ssh instead of plink wrappers for my work in command line and solve at least some of my issues.

The answers here are still:
* Yes ssh-agent does say which key it wants, but only after it requests a list of all keys.
* Yes KeeAgent supports ssh-agent protocol - it is exactly the same as PuTTY/Pagent protocol.

**Comment by dlech** [comment]
I will probably be releasing the current beta as stable in a few months. Hopefully the new features in the beta cover most cases here. If you think there is further room for improvement, now is a good time to discuss it. Or if you feel the new features are adequate, we can close this issue.

**Comment by addshore** [comment]
I would still love to potentially see something like https://github.com/dlech/KeeAgent/issues/120#issuecomment-139740152 ;)

**Comment by dlech** [comment]
Closing due to no response from opener.
