### ISSUE TITLE
Could not load file on opening KeepassDB when using references.

### ISSUE THREAD

**Issue by JoschHH** [dlech/KeeAgent#94]
When opening the KeePass database, I get the following message. "KeeAgent Error - Could not load file" (same as on #71 )

Setup: KeePass 2.28, KeeAgent 0.4.1, SSH Keys stored as attachments in the keepass entry inside the KeepassDBX. 

Does this relate to the same issue #71  "Keepass changed store-mechanism" or is it something new ? 
![keeagent-onlonad-fehler](https://cloud.githubusercontent.com/assets/10339586/5569233/0db86736-8f6d-11e4-8d59-1de7d953b65b.PNG)

**Comment by JoschHH** [comment]
Hi David, 
got 0.5.4 installed - it showed me an entry with SSH key attached AND with
"password Reference" used. Once I removed the reference and stored the password
directly, the message disappeard.

Regards, Josh

**Comment by dlech** [comment]
I've changed the title to reflect the actual problem. It should be possible to fix this if you want to use references in the password field.

**Comment by JoschHH** [comment]
Hi David,
A workaround exists and  wonder how many others use reference pointers, so inwould rate that a medium prio :) for slow days ;)

Thanks for your support

---
Ab in den Urlaubsflieger ... Umstieg in Frankfurt ... Weiteres Checkin nicht möglich, weil der Name auf einer computergenerierten NoFly Liste steht. Wollen wir wirklich die vollautomatisierte Überwachung ? 

"Demokratie" heisst auch "Privatsphäre" ... und "Mitmachen"!

**Comment by dlech** [comment]
Fix is released in v0.7.6.

http://lechnology.com/2015/09/keeagent-beta-v0-7-6-released/
