### ISSUE TITLE
Provide build instructions

### ISSUE THREAD

**Issue by manwesulimo2004** [dlech/KeeAgent#95]
It would be great to have step by step instruction on how to build this.

**Comment by dlech** [comment]
Have you seen <https://github.com/dlech/KeeAgent/wiki/Developer-Notes>?

**Comment by manwesulimo2004** [comment]
Thanks for pointing that out. I completely missed those docs. Perhaps it would make sense to put a link in the readme file.

**Comment by dlech** [comment]
> Actually copy-pasting the contents would be even better than simply providing a link.

Done!
