### ISSUE TITLE
Same password for number of keys

### ISSUE THREAD

**Issue by egort** [dlech/KeeAgent#96]
Hi!
In pageant utility, if you select and add multiple keys with the same passwords, you need enter password only one time, regardless amount of keys. Is it possible to realize the same behavior in KeeAgent?

**Comment by dlech** [comment]
This sounds like #94. Is this what you are asking for? 

Although since KeePass remembers your passwords, each key can have a different passphrase and you do not have to enter any of them.

**Comment by egort** [comment]
Not exactly. I talk about keys which stored in file, not inside the KeePass db. Key passphrases also not stored in KeePass db, I enter passphrase for each key each time after starting KeePass.

**Comment by dlech** [comment]
It is a "feature" of KeeAgent that it does not keep passphrases in memory. If you do not want to store the passphrase in KeePass, then I would suggest using KeeAgent in "Client Mode". [More info...](lechnology.com/software/keeagent/usage/options-and-settings/#global-options)

**Comment by egort** [comment]
Sorry, it seems I can't explain correctly)
Did you use pageant (from www.chiark.greenend.org.uk)? When you select multiple key files with the same passphrase, and then add them (all at one time) in pageant, you have to enter passphrase only one time for all selected key files.

**Comment by dlech** [comment]
Yes, I understand what you are saying. This is why I suggested using Client Mode. In Client Mode, you actually run pageant before start KeePass. Then, when KeePass starts, the KeeAgent plugin will load any keys in the database into pageant. Then you can use pageant to also load "keys which stored in file, not inside the KeePass db. Key passphrases also not stored in KeePass db" in pageant and you will only have to enter the passphrase once.

**Comment by dlech** [comment]
Fix is released in v0.7.6.

http://lechnology.com/2015/09/keeagent-beta-v0-7-6-released/

**Comment by egort** [comment]
Thank you very much! 
btw http://lechnology.com/2015/09/keeagent-beta-v0-7-6-released/ show download link to previous (0.7.4) version

**Comment by dlech** [comment]
You are welcome. And thanks for letting me know - I've fixed the link now.
