### ISSUE TITLE
ed25519 keys support

### ISSUE THREAD

**Issue by grazzolini** [dlech/KeeAgent#97]
This new key format is faster and smaller than the others. It would make keys more easily attached to the database.

**Comment by dlech** [comment]
Pull requests are welcome, otherwise I will look into it when I get a chance.

**Comment by grazzolini** [comment]
From a quick look into BouncyCastle, it does not support ed25519. I might be wrong. Anyway, I'll try to take a look into the KeeAgent source code and see if I can implement it.

**Comment by dlech** [comment]
Useful links from @kevinvalk:

The commit responsible for the new change is http://marc.info/?l=openbsd-cvs&m=138633690918227&w=2.
PROTOCOL description https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.key.
General information http://www.tedunangst.com/flak/post/new-openssh-key-format-and-bcrypt-pbkdf

**Comment by dlech** [comment]
This has been released in [beta v0.7.0](http://lechnology.com/wp-content/uploads/2015/06/KeeAgent_Beta_v0.7.0.zip). If there are an problems, please open a new issue.
