### ISSUE TITLE
Create chocolatey package to simplify windows installation

### ISSUE THREAD

**Issue by DavidPowell** [dlech/KeeAgent#98]
Downloading and installing KeeAgent under windows is slightly tedious at the moment. This process could be automated by creating a Chocolatey package, enabling downloading, installation and upgrade with a single command, similar to apt-get et al under Linux.

A package for [KeePass](https://chocolatey.org/packages/keepass) already exists, and the [KeePassHTTP](https://chocolatey.org/packages/keepass-keepasshttp) plugin also has a package, which suggests that it should be feasible to do something similar for KeeAgent.

**Comment by dlech** [comment]
Looks interesting. However, I don't use Windows on a daily basis, so I don't have much motivation to maintain a package for Chocolatey. Though I would be glad to answer questions for anyone that would like to do so.

**Comment by DavidPowell** [comment]
I've made an attempt at doing this myself, although I'm not very familiar with chocolatey and windows powershell programming. There is now a package available at https://chocolatey.org/packages/keepass-keeagent/0.6.0, currently awaiting moderation. Once any bugs are fixed and the package is accepted I'll let you know.

**Comment by dlech** [comment]
Cool. I'll add a link to this from my website once it get moderated. And just a heads up, I have a couple bug fixes, so I'll be doing a release for v0.6.1 soon. Actually, I think I'll do that right now....

**Comment by dlech** [comment]
New download URL is http://lechnology.com/wp-content/uploads/2015/04/KeeAgent_v0.6.1.zip

**Comment by dlech** [comment]
Also re: the line

    $installDir = $installPath + "plugins\"

Plugins can be installed in any subdirectory of the KeePass install directory. I would suggest using

    $installDir = $installPath + "KeeAgent\"

instead. This way it wont conflict with any other plugins. The zip file contains changelog and copying files that have generic names that are likely to conflict with other plugins.

**Comment by DavidPowell** [comment]
I decided that `plugins\KeeAgent` was the best install dir, and updated the 0.6.0 package accordingly. I also created the 0.6.1 package as well.

I've subscribed to KeeAgent tags on github, so I should get notified automatically whenever you create a new version and it's only a few lines to update the package.

**Comment by dlech** [comment]
Sounds like you know what you are doing. :wink:

**Comment by DavidPowell** [comment]
Finally the chocolatey package was approved, after an extremely protracted approval process. The latest package is available from https://chocolatey.org/packages/keepass-keeagent/, and I will keep this up to date when new (non beta) versions are updated.

@dlech - You may wish to mention this as an option for windows users on your installation instructions page, as it considerably simplifies the installation process.

**Comment by dlech** [comment]
Thanks for the update. I've added a link to the package from my website.
