### ISSUE TITLE
Error loading OpenSSH RSA keys

### ISSUE THREAD

**Issue by LeoVerto** [dlech/KeeAgent#99]
I generated a few RSA keys using mysys2 and attempted to add them to KeeAgent. Whether with our without password, I always get the generic error message.

**Comment by dlech** [comment]
When do you get the error? When loading the key into the agent?

Also, what is your operating system, KeePass version, and KeeAgent version?

Can you generate a new key and post it somewhere so I can try it out?

**Comment by LeoVerto** [comment]
Sorry, forgot the basic bug report stuff.

Win 7, KeePass 2.28, KeeAgent 0.6.0.0.

I get the error whenever I try to load one of the keys manually or KeeAgent tries to do so automatically.

I am actually currently failing to reproduce the error with new keys, which is quite interesting considering nothing worked earlier.

**Comment by dlech** [comment]
Well, if you do find a key that doesn't work, send it to me.

**Comment by LeoVerto** [comment]
Found the problem, for some reason ssh-keygen generated keys of a different type with the header
` -----BEGIN OPENSSH PRIVATE KEY----- `
Here's a Gist with examples. https://gist.github.com/LeoVerto/1137e78d7105dd462b11

**Comment by dlech** [comment]
So is this something we should add support for?

**Comment by LeoVerto** [comment]
Seeing as it a method to increase key/passphrase strength, it would probably make sense to support it.

**Comment by dlech** [comment]
OK. Since I just did a major release, it could be a while before I get around to looking at this, but I'll have a look at adding it in the next beta release. If anyone wants to have a go at adding before then, I'll be glad to take a pull request.

**Comment by dlech** [comment]
By the way, thank you for figuring all this stuff out - it will make it easy for me to implement.

**Comment by LeoVerto** [comment]
No problem, thank *you* for making this and Keebuntu, greatly improving usability across platforms!

**Comment by kevinvalk** [comment]
This is a duplicate for ticket #97. OpenSSH has added support for a new key format to prevent brute forcing by using KDF.
The commit responsible for the new change is http://marc.info/?l=openbsd-cvs&m=138633690918227&w=2.
PROTOCOL description https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.key.
General information http://www.tedunangst.com/flak/post/new-openssh-key-format-and-bcrypt-pbkdf

Good work @dlech , I would love to start using your KeeAgent, however, I have my keys in this "new" format.

**Comment by dlech** [comment]
Thanks for clearing that up (about `-----BEGIN OPENSSH PRIVATE KEY----` == ed25519). Closing this on as duplicate.

**Comment by dlech** [comment]
I've started working on this and found that `-----BEGIN OPENSSH PRIVATE KEY----` != ed25519.

ed25519 is a new public key algroithm and `-----BEGIN OPENSSH PRIVATE KEY----` is a new private key format. These are 2 different features that were introduced in the same version of openssh.

So reopening as this issue is about the file format (with rsa in this case) and not ed25519.

**Comment by LeoVerto** [comment]
Thank you :D

**Comment by dlech** [comment]
This has been released in [beta v0.7.0](http://lechnology.com/wp-content/uploads/2015/06/KeeAgent_Beta_v0.7.0.zip). If there are an problems, please open a new issue.
